"""
SAP Security Controls Library

Standard SAP profile parameter security controls covering:
- Authentication & Password Policy
- RFC Security
- Gateway Security
- Audit Logging
- User Administration
- System Hardening
- Network / ICM Security
- Table Maintenance
- Change Management

These are the "global templates" — control_ids prefixed with SAP-.
Customers can adopt them and create tenant-specific CUST- variants.
"""

from typing import List, Dict, Any

SAP_CONTROLS_LIBRARY: List[Dict[str, Any]] = [

    # ─── Authentication & Password ────────────────────────────────────────────

    {
        "control_id": "SAP-AUTH-001",
        "control_name": "Maximum Invalid Login Attempts",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "General Authentication",
        "description": "Limits the number of consecutive failed login attempts before the user account is locked. Reduces brute-force and credential-stuffing attacks.",
        "purpose": "Prevent unauthorized access via brute-force login attempts.",
        "procedure": "Check profile parameter login/max_invalid_attempts. Value should be 3–5.",
        "profile_parameter": "login/max_invalid_attempts",
        "expected_value": "3",
        "default_risk_rating": "RED",
        "recommendation": "Set login/max_invalid_attempts to 3 or 5 at most. Values above 5 are non-compliant.",
        "is_automated": True,
        "compliance_frameworks": ["SOX", "ISO27001", "PCI-DSS", "NIST"],
        "value_mappings": [
            {"value_condition": "lte", "value_pattern": "5", "risk_rating": "GREEN", "recommendation": "Compliant — value ≤ 5"},
            {"value_condition": "between", "value_pattern": "6-9", "risk_rating": "YELLOW", "recommendation": "Acceptable but tighten to ≤ 5"},
            {"value_condition": "gte", "value_pattern": "10", "risk_rating": "RED", "recommendation": "Too permissive — reduce to ≤ 5 immediately"},
        ],
    },
    {
        "control_id": "SAP-AUTH-002",
        "control_name": "Minimum Password Length",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "General Authentication",
        "description": "Enforces a minimum number of characters for SAP user passwords.",
        "purpose": "Prevent weak passwords that can be easily guessed or cracked.",
        "procedure": "Check profile parameter login/min_password_lng.",
        "profile_parameter": "login/min_password_lng",
        "expected_value": "8",
        "default_risk_rating": "YELLOW",
        "recommendation": "Set to at least 8. Recommended 12+ for privileged accounts.",
        "is_automated": True,
        "compliance_frameworks": ["SOX", "ISO27001", "PCI-DSS", "NIST"],
        "value_mappings": [
            {"value_condition": "gte", "value_pattern": "12", "risk_rating": "GREEN", "recommendation": "Strong password length policy"},
            {"value_condition": "between", "value_pattern": "8-11", "risk_rating": "YELLOW", "recommendation": "Acceptable — consider raising to 12+"},
            {"value_condition": "lte", "value_pattern": "7", "risk_rating": "RED", "recommendation": "Non-compliant — increase immediately"},
        ],
    },
    {
        "control_id": "SAP-AUTH-003",
        "control_name": "Password Expiration Period",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "General Authentication",
        "description": "Forces users to change passwords after a defined number of days.",
        "purpose": "Limit the window of opportunity if credentials are compromised.",
        "procedure": "Check login/password_expiration_time. Value is in days; 0 means never expires.",
        "profile_parameter": "login/password_expiration_time",
        "expected_value": "90",
        "default_risk_rating": "YELLOW",
        "recommendation": "Set to 90 days maximum. Value 0 (never expire) is a critical finding.",
        "is_automated": True,
        "compliance_frameworks": ["SOX", "PCI-DSS", "ISO27001"],
        "value_mappings": [
            {"value_condition": "between", "value_pattern": "30-90", "risk_rating": "GREEN", "recommendation": "Compliant"},
            {"value_condition": "between", "value_pattern": "91-180", "risk_rating": "YELLOW", "recommendation": "Consider reducing to 90 days"},
            {"value_condition": "eq", "value_pattern": "0", "risk_rating": "RED", "recommendation": "Passwords never expire — set expiration immediately"},
            {"value_condition": "gte", "value_pattern": "181", "risk_rating": "RED", "recommendation": "Too long — reduce to 90 days"},
        ],
    },
    {
        "control_id": "SAP-AUTH-004",
        "control_name": "Password History Size",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "General Authentication",
        "description": "Prevents users from reusing recent passwords.",
        "purpose": "Ensure password rotation is meaningful and not circular.",
        "procedure": "Check login/password_history_size.",
        "profile_parameter": "login/password_history_size",
        "expected_value": "5",
        "default_risk_rating": "YELLOW",
        "recommendation": "Set to at least 5. Value 0 disables history check.",
        "is_automated": True,
        "compliance_frameworks": ["PCI-DSS", "ISO27001", "NIST"],
        "value_mappings": [
            {"value_condition": "gte", "value_pattern": "5", "risk_rating": "GREEN", "recommendation": "Compliant"},
            {"value_condition": "between", "value_pattern": "1-4", "risk_rating": "YELLOW", "recommendation": "Increase to at least 5"},
            {"value_condition": "eq", "value_pattern": "0", "risk_rating": "RED", "recommendation": "Password history disabled — enable immediately"},
        ],
    },
    {
        "control_id": "SAP-AUTH-005",
        "control_name": "Automatic User Unlock After Failed Logins",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "General Authentication",
        "description": "Controls whether locked users are automatically unlocked after a timeout period.",
        "purpose": "Prevent locked accounts from automatically becoming accessible without admin action.",
        "procedure": "Check login/failed_user_auto_unlock. Value 1 = auto-unlock (bad), 0 = manual unlock required.",
        "profile_parameter": "login/failed_user_auto_unlock",
        "expected_value": "0",
        "default_risk_rating": "RED",
        "recommendation": "Set to 0 to require manual unlock. Auto-unlock undermines lockout policy.",
        "is_automated": True,
        "compliance_frameworks": ["PCI-DSS", "ISO27001", "SOX"],
        "value_mappings": [
            {"value_condition": "eq", "value_pattern": "0", "risk_rating": "GREEN", "recommendation": "Manual unlock required — compliant"},
            {"value_condition": "eq", "value_pattern": "1", "risk_rating": "RED", "recommendation": "Auto-unlock enabled — set to 0 immediately"},
        ],
    },
    {
        "control_id": "SAP-AUTH-006",
        "control_name": "Multiple GUI Login Sessions",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "General Authentication",
        "description": "Limits concurrent login sessions per user ID.",
        "purpose": "Prevent credential sharing and detect compromised accounts.",
        "procedure": "Check login/disable_multi_gui_login.",
        "profile_parameter": "login/disable_multi_gui_login",
        "expected_value": "1",
        "default_risk_rating": "YELLOW",
        "recommendation": "Set to 1 to restrict to single session or configure login/multi_login_users for specific exceptions.",
        "is_automated": True,
        "compliance_frameworks": ["SOX", "PCI-DSS"],
        "value_mappings": [
            {"value_condition": "eq", "value_pattern": "1", "risk_rating": "GREEN", "recommendation": "Multiple sessions disabled"},
            {"value_condition": "eq", "value_pattern": "0", "risk_rating": "YELLOW", "recommendation": "Multiple sessions allowed — review policy"},
        ],
    },
    {
        "control_id": "SAP-AUTH-007",
        "control_name": "SAP* User Default Password Disabled",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "User Administration",
        "description": "Disables automatic creation of SAP* user with default password PASS in new clients.",
        "purpose": "Prevent use of the emergency backdoor user SAP* with default credentials.",
        "procedure": "Check login/no_automatic_user_sapstar. Should be 1.",
        "profile_parameter": "login/no_automatic_user_sapstar",
        "expected_value": "1",
        "default_risk_rating": "RED",
        "recommendation": "Set to 1. SAP* with default password PASS is a critical vulnerability.",
        "is_automated": True,
        "compliance_frameworks": ["SOX", "PCI-DSS", "ISO27001", "NIST"],
    },
    {
        "control_id": "SAP-AUTH-008",
        "control_name": "Password Change Wait Time",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "General Authentication",
        "description": "Minimum number of days before a password can be changed again.",
        "purpose": "Prevent users from immediately cycling through passwords to reuse old ones.",
        "procedure": "Check login/password_change_waittime.",
        "profile_parameter": "login/password_change_waittime",
        "expected_value": "1",
        "default_risk_rating": "YELLOW",
        "recommendation": "Set to 1 or more days.",
        "is_automated": True,
        "compliance_frameworks": ["PCI-DSS", "ISO27001"],
    },
    {
        "control_id": "SAP-AUTH-009",
        "control_name": "Password Complexity Policy Enforcement",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "General Authentication",
        "description": "Enforces that new passwords comply with the currently active password policy.",
        "purpose": "Ensure all new passwords meet complexity requirements.",
        "procedure": "Check login/password_compliance_to_current_policy. Should be 1.",
        "profile_parameter": "login/password_compliance_to_current_policy",
        "expected_value": "1",
        "default_risk_rating": "YELLOW",
        "recommendation": "Set to 1 to enforce compliance with current policy for all password changes.",
        "is_automated": True,
        "compliance_frameworks": ["PCI-DSS", "ISO27001", "NIST"],
    },

    # ─── GUI / Session Security ────────────────────────────────────────────────

    {
        "control_id": "SAP-GUI-001",
        "control_name": "GUI Auto-Logout Timeout",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "General Authentication",
        "description": "Automatically logs out inactive GUI sessions after a specified period.",
        "purpose": "Prevent unauthorized use of unattended workstations.",
        "procedure": "Check rdisp/gui_auto_logout. Value in seconds; 0 disables auto-logout.",
        "profile_parameter": "rdisp/gui_auto_logout",
        "expected_value": "1800",
        "default_risk_rating": "YELLOW",
        "recommendation": "Set to 900–1800 seconds (15–30 minutes). Value 0 is a critical finding.",
        "is_automated": True,
        "compliance_frameworks": ["PCI-DSS", "ISO27001", "SOX"],
        "value_mappings": [
            {"value_condition": "between", "value_pattern": "600-1800", "risk_rating": "GREEN", "recommendation": "Auto-logout configured appropriately"},
            {"value_condition": "between", "value_pattern": "1801-3600", "risk_rating": "YELLOW", "recommendation": "Consider reducing timeout"},
            {"value_condition": "eq", "value_pattern": "0", "risk_rating": "RED", "recommendation": "Auto-logout disabled — enable immediately"},
            {"value_condition": "gte", "value_pattern": "3601", "risk_rating": "YELLOW", "recommendation": "Timeout too long — reduce to ≤ 30 minutes"},
        ],
    },

    # ─── RFC Security ─────────────────────────────────────────────────────────

    {
        "control_id": "SAP-RFC-001",
        "control_name": "RFC Authority Check",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "RFC Security",
        "description": "Enforces authorization checks for RFC function module calls.",
        "purpose": "Prevent unauthorized execution of RFC function modules from remote systems.",
        "procedure": "Check auth/rfc_authority_check. Should be 1 (enabled).",
        "profile_parameter": "auth/rfc_authority_check",
        "expected_value": "1",
        "default_risk_rating": "RED",
        "recommendation": "Set to 1. When disabled (0), any RFC caller can execute any function module without authorization check.",
        "is_automated": True,
        "compliance_frameworks": ["SOX", "PCI-DSS", "ISO27001"],
        "value_mappings": [
            {"value_condition": "eq", "value_pattern": "1", "risk_rating": "GREEN", "recommendation": "RFC authority check enabled"},
            {"value_condition": "eq", "value_pattern": "0", "risk_rating": "RED", "recommendation": "RFC authority check disabled — critical finding"},
        ],
    },
    {
        "control_id": "SAP-RFC-002",
        "control_name": "RFC Reject Expired Passwords",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "RFC Security",
        "description": "Rejects RFC connections using accounts with expired passwords.",
        "purpose": "Prevent RFC connections from bypassing password expiration policy.",
        "procedure": "Check rfc/reject_expired_passwd. Should be 1.",
        "profile_parameter": "rfc/reject_expired_passwd",
        "expected_value": "1",
        "default_risk_rating": "YELLOW",
        "recommendation": "Set to 1 to enforce password expiration for RFC callers.",
        "is_automated": True,
        "compliance_frameworks": ["SOX", "PCI-DSS"],
    },
    {
        "control_id": "SAP-RFC-003",
        "control_name": "Trusted RFC Connections Restricted",
        "business_area": "Security Administration",
        "control_type": "Detective",
        "category": "RFC Security",
        "description": "Reviews trusted RFC connections to ensure they are authorized and necessary.",
        "purpose": "Prevent privilege escalation via overly permissive trusted RFC connections.",
        "procedure": "Review SM59 trusted connections. Check RFCDES table for entries with TRUSTED = 'X'.",
        "profile_parameter": "N/A",
        "expected_value": "Trusted connections documented and justified",
        "default_risk_rating": "YELLOW",
        "recommendation": "Review all trusted RFC connections quarterly. Remove unnecessary trusted connections.",
        "is_automated": False,
        "compliance_frameworks": ["SOX", "ISO27001"],
    },
    {
        "control_id": "SAP-RFC-004",
        "control_name": "Unified Connectivity (UCON) RFC Active",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "RFC Security",
        "description": "UCON framework restricts which RFC function modules are accessible from external systems.",
        "purpose": "Reduce attack surface by whitelisting accessible RFC function modules.",
        "procedure": "Check ucon/rfc_active. Should be 1.",
        "profile_parameter": "ucon/rfc_active",
        "expected_value": "1",
        "default_risk_rating": "YELLOW",
        "recommendation": "Enable UCON RFC monitoring (1) and enforce (2) for SAP systems running NW 7.4+.",
        "is_automated": True,
        "compliance_frameworks": ["ISO27001", "SAP Security Baseline"],
    },

    # ─── Gateway Security ─────────────────────────────────────────────────────

    {
        "control_id": "SAP-GW-001",
        "control_name": "Gateway Security Information File (secinfo)",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "Gateway Security",
        "description": "The secinfo file controls which external programs can be registered at the SAP gateway.",
        "purpose": "Prevent unauthorized programs from registering as RFC server programs.",
        "procedure": "Check gw/sec_info parameter points to a restrictive secinfo file. File should not contain 'P=*'.",
        "profile_parameter": "gw/sec_info",
        "expected_value": "$(DIR_DATA)/secinfo",
        "default_risk_rating": "RED",
        "recommendation": "Configure a restrictive secinfo file. Never use P=* (allow all programs).",
        "is_automated": False,
        "compliance_frameworks": ["SOX", "ISO27001", "SAP Security Baseline"],
    },
    {
        "control_id": "SAP-GW-002",
        "control_name": "Gateway Registration Information File (reginfo)",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "Gateway Security",
        "description": "The reginfo file controls which external RFC server programs can register at the SAP gateway.",
        "purpose": "Prevent malicious programs from hijacking RFC function modules.",
        "procedure": "Check gw/reg_info parameter and review the reginfo file content.",
        "profile_parameter": "gw/reg_info",
        "expected_value": "$(DIR_DATA)/reginfo",
        "default_risk_rating": "RED",
        "recommendation": "Configure restrictive reginfo. Deny all by default, explicitly allow required programs.",
        "is_automated": False,
        "compliance_frameworks": ["SOX", "ISO27001"],
    },
    {
        "control_id": "SAP-GW-003",
        "control_name": "Gateway Monitor Access Restriction",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "Gateway Security",
        "description": "Restricts which hosts can access the gateway monitor (SMGW).",
        "purpose": "Prevent unauthorized administrative access to gateway monitoring.",
        "procedure": "Check gw/monitor parameter. Should be 1 (restricted).",
        "profile_parameter": "gw/monitor",
        "expected_value": "1",
        "default_risk_rating": "YELLOW",
        "recommendation": "Set gw/monitor to 1. Value 2 (no restriction) is a security risk.",
        "is_automated": True,
        "compliance_frameworks": ["ISO27001"],
    },
    {
        "control_id": "SAP-GW-004",
        "control_name": "External RFC Blocking",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "Gateway Security",
        "description": "Blocks external RFC connections from accessing the system when not required.",
        "purpose": "Reduce attack surface by blocking unnecessary external RFC access.",
        "procedure": "Check gw/acl_mode. Should be 1 (ACL based filtering active).",
        "profile_parameter": "gw/acl_mode",
        "expected_value": "1",
        "default_risk_rating": "YELLOW",
        "recommendation": "Enable ACL mode (1) to enforce gateway access control lists.",
        "is_automated": True,
        "compliance_frameworks": ["ISO27001", "SAP Security Baseline"],
    },

    # ─── Audit Logging ────────────────────────────────────────────────────────

    {
        "control_id": "SAP-AUDIT-001",
        "control_name": "Security Audit Log Enabled",
        "business_area": "Audit & Compliance",
        "control_type": "Detective",
        "category": "Audit Logging",
        "description": "The SAP Security Audit Log records security-relevant events in the system.",
        "purpose": "Provide audit trail for forensic investigations and compliance reporting.",
        "procedure": "Check rsau/enable. Should be 1. Also verify filters are configured for critical events.",
        "profile_parameter": "rsau/enable",
        "expected_value": "1",
        "default_risk_rating": "RED",
        "recommendation": "Enable the security audit log (1). Configure filters for: failed logins, transaction starts, RFC calls, user changes.",
        "is_automated": True,
        "compliance_frameworks": ["SOX", "PCI-DSS", "ISO27001", "GDPR", "NIST"],
        "value_mappings": [
            {"value_condition": "eq", "value_pattern": "1", "risk_rating": "GREEN", "recommendation": "Audit log enabled"},
            {"value_condition": "eq", "value_pattern": "0", "risk_rating": "RED", "recommendation": "Audit log disabled — critical compliance gap"},
        ],
    },
    {
        "control_id": "SAP-AUDIT-002",
        "control_name": "Security Audit Log Integrity Protection",
        "business_area": "Audit & Compliance",
        "control_type": "Detective",
        "category": "Audit Logging",
        "description": "Protects audit log files from tampering by enabling integrity protection.",
        "purpose": "Ensure audit logs cannot be altered to cover tracks after an incident.",
        "procedure": "Check rsau/integrity. Should be 1 (integrity enabled).",
        "profile_parameter": "rsau/integrity",
        "expected_value": "1",
        "default_risk_rating": "YELLOW",
        "recommendation": "Enable audit log integrity (1) to prevent log tampering.",
        "is_automated": True,
        "compliance_frameworks": ["SOX", "ISO27001", "NIST"],
    },
    {
        "control_id": "SAP-AUDIT-003",
        "control_name": "Audit Log Disk Space Configuration",
        "business_area": "Audit & Compliance",
        "control_type": "Detective",
        "category": "Audit Logging",
        "description": "Ensures sufficient disk space is allocated for audit log retention.",
        "purpose": "Prevent audit log loss due to disk space exhaustion.",
        "procedure": "Check rsau/max_diskspace/local. Should be configured to retain at least 90 days of logs.",
        "profile_parameter": "rsau/max_diskspace/local",
        "expected_value": "Sufficient for 90+ day retention",
        "default_risk_rating": "YELLOW",
        "recommendation": "Configure adequate disk space. Archive logs to external storage before local retention limit is reached.",
        "is_automated": False,
        "compliance_frameworks": ["SOX", "PCI-DSS", "GDPR"],
    },
    {
        "control_id": "SAP-AUDIT-004",
        "control_name": "System Log Monitoring (SM21)",
        "business_area": "Audit & Compliance",
        "control_type": "Detective",
        "category": "Audit Logging",
        "description": "Regular review of the system log for security events and errors.",
        "purpose": "Detect system errors, unauthorized access attempts, and abnormal system behavior.",
        "procedure": "Review SM21 system log regularly. Configure monitoring tools or scheduled jobs to alert on critical events.",
        "profile_parameter": "N/A",
        "expected_value": "Regular review documented",
        "default_risk_rating": "YELLOW",
        "recommendation": "Automate SM21 log review via CCMS alerts or external SIEM integration.",
        "is_automated": False,
        "compliance_frameworks": ["SOX", "ISO27001"],
    },

    # ─── Authorization & Object Security ─────────────────────────────────────

    {
        "control_id": "SAP-AUTHZ-001",
        "control_name": "Authorization Object Checks Not Disabled",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "Basis & Security Administration",
        "description": "Verifies that authorization object checks have not been disabled globally.",
        "purpose": "Ensure all authorization checks are active and cannot be bypassed.",
        "procedure": "Check auth/object_disabling_active. Should be N (disabled means checks are active).",
        "profile_parameter": "auth/object_disabling_active",
        "expected_value": "N",
        "default_risk_rating": "RED",
        "recommendation": "Set to N. If set to Y, it allows specific auth objects to be deactivated using SU24, creating authorization bypass risk.",
        "is_automated": True,
        "compliance_frameworks": ["SOX", "PCI-DSS", "ISO27001"],
    },
    {
        "control_id": "SAP-AUTHZ-002",
        "control_name": "Auth Check in Role Maintenance",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "Basis & Security Administration",
        "description": "Enforces authorization check activity 06 (create/change) in role maintenance.",
        "purpose": "Ensure that creating or modifying roles requires appropriate authorization.",
        "procedure": "Check auth/check_actvt_6_in_role_maintenance. Should be Y.",
        "profile_parameter": "auth/check_actvt_6_in_role_maintenance",
        "expected_value": "Y",
        "default_risk_rating": "YELLOW",
        "recommendation": "Set to Y to ensure role maintenance changes require proper authorization.",
        "is_automated": True,
        "compliance_frameworks": ["SOX", "ISO27001"],
    },
    {
        "control_id": "SAP-AUTHZ-003",
        "control_name": "Authorization System Access Check",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "Basis & Security Administration",
        "description": "Prevents disabling of authorization checks at the system level.",
        "purpose": "Ensure no global bypass of authorization infrastructure exists.",
        "procedure": "Check auth/system_access_check_off. Should be 0 (checks enabled).",
        "profile_parameter": "auth/system_access_check_off",
        "expected_value": "0",
        "default_risk_rating": "RED",
        "recommendation": "Must be 0. Value 1 disables all system-level auth checks — critical vulnerability.",
        "is_automated": True,
        "compliance_frameworks": ["SOX", "PCI-DSS", "ISO27001"],
    },

    # ─── Table Maintenance ─────────────────────────────────────────────────────

    {
        "control_id": "SAP-TBL-001",
        "control_name": "Table Maintenance Client Setting",
        "business_area": "Basis Administration",
        "control_type": "Preventive",
        "category": "Table Maintenance",
        "description": "Controls whether direct table maintenance (SE16, SM30) is permitted in the production client.",
        "purpose": "Prevent unauthorized direct database changes bypassing application controls.",
        "procedure": "Check client settings in SCC4. Production client should not allow table maintenance without logging.",
        "profile_parameter": "N/A",
        "expected_value": "No table maintenance without logging in production",
        "default_risk_rating": "RED",
        "recommendation": "Set production client to 'Changes to Repository and cross-client Customizing allowed'. Disable direct table maintenance.",
        "is_automated": False,
        "compliance_frameworks": ["SOX", "ITGC"],
    },
    {
        "control_id": "SAP-TBL-002",
        "control_name": "SE16N Hidden Functions Restricted",
        "business_area": "Basis Administration",
        "control_type": "Preventive",
        "category": "Table Maintenance",
        "description": "SE16N has a hidden function allowing direct table editing. This must be restricted.",
        "purpose": "Prevent misuse of SE16N hidden edit mode to modify production data directly.",
        "procedure": "Verify authorization object S_TABU_NAM restricts access to SE16N edit mode. Check for SAP Note 1420281.",
        "profile_parameter": "N/A",
        "expected_value": "S_TABU_NAM restricted for production users",
        "default_risk_rating": "RED",
        "recommendation": "Apply SAP Note 1420281. Restrict S_TABU_NAM authorization object in production.",
        "is_automated": False,
        "compliance_frameworks": ["SOX", "ISO27001"],
    },

    # ─── Change Management ─────────────────────────────────────────────────────

    {
        "control_id": "SAP-CHG-001",
        "control_name": "Production Client Change Option",
        "business_area": "Change Management",
        "control_type": "Preventive",
        "category": "Change Management",
        "description": "Ensures the production client is locked against unauthorized customizing changes.",
        "purpose": "Enforce formal change management — all changes must go through transport.",
        "procedure": "Check SCC4 for production client. Change option should be 'No changes allowed'.",
        "profile_parameter": "N/A",
        "expected_value": "Production client locked for changes",
        "default_risk_rating": "RED",
        "recommendation": "Set production client change option to 'No changes to Customizing objects allowed'.",
        "is_automated": False,
        "compliance_frameworks": ["SOX", "ITGC", "ISO27001"],
    },
    {
        "control_id": "SAP-CHG-002",
        "control_name": "Transport System Configuration",
        "business_area": "Change Management",
        "control_type": "Preventive",
        "category": "Change Management",
        "description": "Validates the SAP transport management system is correctly configured for three-system landscape.",
        "purpose": "Ensure all changes follow DEV → QA → PROD transport path with proper approvals.",
        "procedure": "Review STMS configuration. Verify transport routes enforce DEV→QA→PRD flow.",
        "profile_parameter": "N/A",
        "expected_value": "Three-system landscape with approval workflow",
        "default_risk_rating": "YELLOW",
        "recommendation": "Configure transport routes in STMS. Enable transport approvals for production imports.",
        "is_automated": False,
        "compliance_frameworks": ["SOX", "ITGC"],
    },
    {
        "control_id": "SAP-CHG-003",
        "control_name": "ABAP Debugging in Production Restricted",
        "business_area": "Change Management",
        "control_type": "Preventive",
        "category": "Change Management",
        "description": "Restricts the use of ABAP debugger with replace mode in production systems.",
        "purpose": "Prevent unauthorized runtime data manipulation via debug sessions.",
        "procedure": "Check authorization object S_DEVELOP with activity 03 (debug). Should be tightly restricted.",
        "profile_parameter": "N/A",
        "expected_value": "S_DEVELOP ACTVT 03 restricted in production",
        "default_risk_rating": "RED",
        "recommendation": "Remove S_DEVELOP authorization with debug activities from all production roles.",
        "is_automated": False,
        "compliance_frameworks": ["SOX", "PCI-DSS", "ISO27001"],
    },

    # ─── Network / ICM Security ───────────────────────────────────────────────

    {
        "control_id": "SAP-ICM-001",
        "control_name": "HTTP to HTTPS Redirect",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "OS Commands Management",
        "description": "Ensures all HTTP traffic is redirected to HTTPS to enforce encrypted communication.",
        "purpose": "Prevent credential and session data interception over unencrypted HTTP.",
        "procedure": "Check ICM profile parameters icm/server_port_* for HTTP redirect or SSL-only configuration.",
        "profile_parameter": "icm/server_port_1",
        "expected_value": "PROT=HTTPS or HTTP redirect configured",
        "default_risk_rating": "YELLOW",
        "recommendation": "Configure ICM to redirect all HTTP to HTTPS. Disable plain HTTP ports if possible.",
        "is_automated": False,
        "compliance_frameworks": ["PCI-DSS", "ISO27001", "GDPR"],
    },
    {
        "control_id": "SAP-ICM-002",
        "control_name": "Secure Network Communications (SNC) Enabled",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "OS Commands Management",
        "description": "SNC encrypts communication between SAP GUI clients and the application server.",
        "purpose": "Protect authentication credentials and session data from network interception.",
        "procedure": "Check snc/enable. Should be 1 for production systems with external access.",
        "profile_parameter": "snc/enable",
        "expected_value": "1",
        "default_risk_rating": "YELLOW",
        "recommendation": "Enable SNC (1) for all external-facing application servers. Configure SNC with at least quality level 3 (encryption).",
        "is_automated": True,
        "compliance_frameworks": ["PCI-DSS", "ISO27001"],
    },

    # ─── Background Jobs ──────────────────────────────────────────────────────

    {
        "control_id": "SAP-BJ-001",
        "control_name": "Background Job User IDs Reviewed",
        "business_area": "Basis Administration",
        "control_type": "Detective",
        "category": "Background job Administration",
        "description": "Background jobs running under privileged user IDs should be reviewed regularly.",
        "purpose": "Prevent privilege escalation via background jobs running under admin accounts.",
        "procedure": "Review SM37 for jobs running under SAP*, DDIC, or administrator accounts. Verify all scheduled jobs are authorized.",
        "profile_parameter": "N/A",
        "expected_value": "No production batch jobs running under DDIC or SAP*",
        "default_risk_rating": "YELLOW",
        "recommendation": "Create dedicated technical batch user IDs with minimal required authorizations. Replace DDIC/SAP* in all background jobs.",
        "is_automated": False,
        "compliance_frameworks": ["SOX", "ISO27001"],
    },
    {
        "control_id": "SAP-BJ-002",
        "control_name": "Background Processing Security",
        "business_area": "Basis Administration",
        "control_type": "Preventive",
        "category": "Background job Administration",
        "description": "Restricts access to background job administration (SM36, SM37, SM69).",
        "purpose": "Prevent unauthorized scheduling or modification of background jobs.",
        "procedure": "Check S_BTCH_ADM and S_BTCH_JOB authorization objects. Ensure only authorized users can manage jobs.",
        "profile_parameter": "N/A",
        "expected_value": "S_BTCH_ADM restricted to batch admins only",
        "default_risk_rating": "YELLOW",
        "recommendation": "Restrict S_BTCH_ADM to dedicated batch administrators. Restrict S_BTCH_JOB for job owners.",
        "is_automated": False,
        "compliance_frameworks": ["SOX", "ISO27001"],
    },

    # ─── SSO & Identity ───────────────────────────────────────────────────────

    {
        "control_id": "SAP-SSO-001",
        "control_name": "SSO Logon Ticket Validity Period",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "Single Sign-On (SSO) Management",
        "description": "Controls how long SSO logon tickets remain valid.",
        "purpose": "Limit the window for stolen ticket misuse.",
        "procedure": "Check login/ticket_expiration_period. Should be set to a reasonable value (e.g., 8 hours = 28800 seconds).",
        "profile_parameter": "login/ticket_expiration_period",
        "expected_value": "28800",
        "default_risk_rating": "YELLOW",
        "recommendation": "Set ticket validity to match working hours (8h typical). Avoid setting too long.",
        "is_automated": True,
        "compliance_frameworks": ["ISO27001", "SOX"],
    },
    {
        "control_id": "SAP-SSO-002",
        "control_name": "Trust Manager Configuration",
        "business_area": "Security Administration",
        "control_type": "Preventive",
        "category": "Single Sign-On (SSO) Management",
        "description": "Reviews trusted system configurations in the Trust Manager (STRUST) for proper certificate management.",
        "purpose": "Ensure only authorized systems can generate valid SSO tickets accepted by production.",
        "procedure": "Review STRUST trusted system certificates. Verify no expired or unknown certificates.",
        "profile_parameter": "N/A",
        "expected_value": "All trusted certificates documented and current",
        "default_risk_rating": "YELLOW",
        "recommendation": "Review STRUST quarterly. Remove expired or unauthorized certificate entries.",
        "is_automated": False,
        "compliance_frameworks": ["ISO27001", "SOX"],
    },

    # ─── User Administration ──────────────────────────────────────────────────

    {
        "control_id": "SAP-USER-001",
        "control_name": "DDIC User Account Security",
        "business_area": "User Administration",
        "control_type": "Preventive",
        "category": "User Administration",
        "description": "The DDIC user must be locked in production and its password changed from the default.",
        "purpose": "Prevent misuse of DDIC (dictionary user) which has extensive system authorizations.",
        "procedure": "Check if DDIC is locked in SU01 in production client. Password should be set to a complex non-default value.",
        "profile_parameter": "N/A",
        "expected_value": "DDIC locked in production",
        "default_risk_rating": "RED",
        "recommendation": "Lock DDIC in production. Change password from default in all clients.",
        "is_automated": False,
        "compliance_frameworks": ["SOX", "PCI-DSS", "ISO27001"],
    },
    {
        "control_id": "SAP-USER-002",
        "control_name": "Generic / Shared User IDs Restricted",
        "business_area": "User Administration",
        "control_type": "Detective",
        "category": "User Administration",
        "description": "Identifies shared or generic user IDs that multiple people use, preventing individual accountability.",
        "purpose": "Ensure all system access is traceable to a named individual.",
        "procedure": "Review user list in SU01 for generic names (ADMIN, TEST, SUPPORT, etc.). Check for users with no last login or shared by multiple people.",
        "profile_parameter": "N/A",
        "expected_value": "No shared/generic user IDs in production",
        "default_risk_rating": "RED",
        "recommendation": "Remove or lock all generic user IDs. Create named individual accounts.",
        "is_automated": False,
        "compliance_frameworks": ["SOX", "PCI-DSS", "GDPR", "ISO27001"],
    },
    {
        "control_id": "SAP-USER-003",
        "control_name": "Dormant User Account Review",
        "business_area": "User Administration",
        "control_type": "Detective",
        "category": "User Administration",
        "description": "Identifies user accounts that have not logged in for an extended period.",
        "purpose": "Prevent use of abandoned or orphaned accounts for unauthorized access.",
        "procedure": "Check users with no login in last 90 days (USR02 table, TRDAT/LDATE columns). Include BNAME, GLTGB, USTYP.",
        "profile_parameter": "N/A",
        "expected_value": "No active users with 90+ days inactivity",
        "default_risk_rating": "YELLOW",
        "recommendation": "Lock accounts inactive for 90+ days. Disable after 180 days. Review quarterly.",
        "is_automated": True,
        "compliance_frameworks": ["SOX", "PCI-DSS", "ISO27001"],
    },
    {
        "control_id": "SAP-USER-004",
        "control_name": "Emergency / Super User Account Control",
        "business_area": "User Administration",
        "control_type": "Detective",
        "category": "User Administration",
        "description": "Emergency accounts (super users) should be tightly controlled with time-limited activation and full logging.",
        "purpose": "Ensure emergency access is accountable and auditable.",
        "procedure": "Identify all users with SAP_ALL or extensive authorizations in USR02/AGR_USERS. Verify each has documented justification.",
        "profile_parameter": "N/A",
        "expected_value": "All super users documented and monitored",
        "default_risk_rating": "RED",
        "recommendation": "Implement firefighter process for emergency access. Log all super-user sessions.",
        "is_automated": False,
        "compliance_frameworks": ["SOX", "PCI-DSS", "ISO27001"],
    },
    {
        "control_id": "SAP-USER-005",
        "control_name": "User Account Validity Date Configuration",
        "business_area": "User Administration",
        "control_type": "Preventive",
        "category": "User Administration",
        "description": "Ensures user accounts have validity dates set and are not open-ended.",
        "purpose": "Automatically expire accounts for leavers and temporary workers.",
        "procedure": "Check users in USR02 for GLTGB (validity end date). Contractor and temp accounts must have end dates.",
        "profile_parameter": "N/A",
        "expected_value": "All contractor/temp accounts have expiry dates",
        "default_risk_rating": "YELLOW",
        "recommendation": "Set validity end dates for all non-permanent user accounts. Integrate with HR Joiner/Mover/Leaver process.",
        "is_automated": False,
        "compliance_frameworks": ["SOX", "ISO27001"],
    },

    # ─── Code / Developer Security ────────────────────────────────────────────

    {
        "control_id": "SAP-DEV-001",
        "control_name": "Development Access in Production Restricted",
        "business_area": "Change Management",
        "control_type": "Preventive",
        "category": "Code Security",
        "description": "Verifies that ABAP development authorizations (S_DEVELOP) are not assigned in production.",
        "purpose": "Prevent direct code changes in production that bypass change management.",
        "procedure": "Check AGR_1251 for roles containing S_DEVELOP in production. DEVCLASS and ACTVT 01/02 should not exist.",
        "profile_parameter": "N/A",
        "expected_value": "No S_DEVELOP create/change in production roles",
        "default_risk_rating": "RED",
        "recommendation": "Remove S_DEVELOP with activities 01 (create), 02 (change), 16 (execute) from all production roles.",
        "is_automated": False,
        "compliance_frameworks": ["SOX", "ISO27001", "ITGC"],
    },
    {
        "control_id": "SAP-DEV-002",
        "control_name": "Code Vulnerability Scanning",
        "business_area": "Change Management",
        "control_type": "Detective",
        "category": "Code Security",
        "description": "Custom ABAP code is scanned for security vulnerabilities before transport to production.",
        "purpose": "Prevent SQL injection, path traversal, and other code-level vulnerabilities in custom developments.",
        "procedure": "Run SAP Code Inspector (SCI) or ATC checks on all custom code before production transport. Critical findings must be resolved.",
        "profile_parameter": "N/A",
        "expected_value": "All transports pass ATC/SCI security checks",
        "default_risk_rating": "YELLOW",
        "recommendation": "Integrate ATC security checks into transport workflow. Block transports with critical findings.",
        "is_automated": True,
        "compliance_frameworks": ["ISO27001", "OWASP", "NIST"],
    },

    # ─── OS / System Level ────────────────────────────────────────────────────

    {
        "control_id": "SAP-OS-001",
        "control_name": "OS Commands via SAP Restricted",
        "business_area": "Basis Administration",
        "control_type": "Preventive",
        "category": "OS Commands Management",
        "description": "Restricts execution of OS-level commands from within SAP (SM69, SM49).",
        "purpose": "Prevent privilege escalation from SAP to underlying operating system.",
        "procedure": "Review SM69 external commands. Check authorization object S_RZL_ADM. Verify no unrestricted OS access.",
        "profile_parameter": "N/A",
        "expected_value": "SM69 OS commands restricted and reviewed",
        "default_risk_rating": "RED",
        "recommendation": "Remove S_RZL_ADM from all non-Basis roles. Review and restrict all SM69 command definitions.",
        "is_automated": False,
        "compliance_frameworks": ["SOX", "PCI-DSS", "ISO27001"],
    },
    {
        "control_id": "SAP-OS-002",
        "control_name": "SAP Message Server Access Restriction",
        "business_area": "Basis Administration",
        "control_type": "Preventive",
        "category": "OS Commands Management",
        "description": "Restricts access to the SAP message server administrative interface.",
        "purpose": "Prevent unauthorized access to the message server which can disrupt the entire SAP landscape.",
        "procedure": "Check ms/server_port and ms/acl_info. Message server admin port should be firewall-restricted.",
        "profile_parameter": "ms/server_port",
        "expected_value": "Admin port firewall-restricted",
        "default_risk_rating": "YELLOW",
        "recommendation": "Restrict message server admin port to trusted hosts only via firewall and ms/acl_info.",
        "is_automated": False,
        "compliance_frameworks": ["ISO27001", "SAP Security Baseline"],
    },

    # ─── Data Privacy ─────────────────────────────────────────────────────────

    {
        "control_id": "SAP-PRIV-001",
        "control_name": "Personal Data Access Logging",
        "business_area": "Data Privacy",
        "control_type": "Detective",
        "category": "Data Privacy",
        "description": "Enables read access logging for sensitive personal data fields (GDPR compliance).",
        "purpose": "Provide audit trail for personal data access for GDPR Article 30 compliance.",
        "procedure": "Check that Read Access Logging (RAL) is configured in SRALMANAGER for sensitive tables/fields (HR, customer PII).",
        "profile_parameter": "N/A",
        "expected_value": "RAL enabled for all PII-containing tables",
        "default_risk_rating": "YELLOW",
        "recommendation": "Configure Read Access Logging for all tables containing personal data (HR, FI customer data). Requires SAP NW 7.5+.",
        "is_automated": True,
        "compliance_frameworks": ["GDPR", "CCPA", "ISO27001"],
    },
    {
        "control_id": "SAP-PRIV-002",
        "control_name": "Information Lifecycle Management (ILM) Configuration",
        "business_area": "Data Privacy",
        "control_type": "Preventive",
        "category": "Data Privacy",
        "description": "ILM manages data retention and deletion for personal data in compliance with GDPR right-to-erasure.",
        "purpose": "Ensure personal data is retained only for legal minimum and deleted thereafter.",
        "procedure": "Verify ILM policies are configured for relevant data objects. Check IRMPOL_DISPLAY for active policies.",
        "profile_parameter": "N/A",
        "expected_value": "ILM policies defined for all PII data objects",
        "default_risk_rating": "YELLOW",
        "recommendation": "Implement ILM data retention policies aligned with legal requirements for each country/region.",
        "is_automated": True,
        "compliance_frameworks": ["GDPR", "CCPA"],
    },
]
