# Database Models
from .base import Base
from .tenant import Tenant, TenantStatus, TenantTier, AdminSession
from .user import User, Role, UserRole, UserEntitlement
from .risk import RiskViolation, MitigationControl, RiskRuleModel, TenantRulePreference
from .firefighter import FirefighterRequest, FirefighterSession, FirefighterActivity, FirefighterIDConfig
from .audit import AuditLog, AccessRequestLog, CertificationCampaignLog, CertificationItemLog
from .approver import ApproverModel, ApprovalRuleModel
from .sap_security_controls import (
    SAPSecurityControl,
    ControlValueMapping,
    ControlEvaluation,
    ControlException,
    SystemSecurityProfile,
    RiskRating,
    ControlCategory,
    ControlStatus,
    EvaluationStatus
)
from .operations import (
    OrgRule,
    OrgUserAssignment,
    OrgRoleRestriction,
    BulkJob,
    SyncConfig,
    SyncHistory,
    TransportRecord,
    NotificationRecord,
    NotificationPreference,
    CustomTcodeRecord,
    ModelTemplate,
    MitigationMonitorRecord,
    OrchestrationContextRecord,
    ShoppingCartModel,
)
from .intelligence import (
    TroubleshooterKBUser,
    TroubleshooterKBRole,
    TroubleshooterKBTransaction,
    RoleIntelligenceRecord,
    DriftSnapshot,
    FioriAppRecord,
    IdentityAccount,
    IdentityClusterRecord,
    MigrationMapping,
    TimelineEvent,
    AuditEvidenceItem,
)
from .engines import (
    EvidenceRecord as EvidenceRecordDB,
    FindingRecord as FindingRecordDB,
    ExecutionPlanRecord,
    DecisionWorkflowRecord,
)

# GRC Foundation (shared across all GRC modules)
from .grc_foundation import (
    OrgUnit,
    OrgUnitType,
    FrameworkDefinition,
    FrameworkType,
    FrameworkRequirement,
)

# Risk Management Module (RM-01 through RM-31 + GovernexPlus gaps)
from .risk_management import (
    EnterpriseRisk,
    RiskCategory,
    RiskStatus,
    RiskAssessment,
    AssessmentType,
    AssessmentStatus,
    RiskAppetite,
    KeyRiskIndicator,
    KRIStatus,
    KRIMeasurement,
    RiskResponse,
    RiskResponseType,
    ResponseStatus,
    RiskIncident,
    IncidentSeverity,
    IncidentStatus,
    # GovernexPlus gap models
    BusinessObjective,
    ObjectiveCategory,
    ObjectiveStatus,
    RiskScenario,
    ScenarioType,
    ScenarioVelocity,
    ScenarioStatus,
    MonteCarloSimulation,
    DistributionType,
    RiskOpportunity,
    OpportunityCategory,
    OpportunityStatus,
)

# Process Control Module (PC-01 through PC-32 + GovernexPlus gaps)
from .process_control import (
    ProcessControl,
    ControlType,
    ControlNature,
    ControlFrequency,
    ControlTest,
    TestType,
    TestResult,
    TestStatus,
    ControlDeficiency,
    DeficiencySeverity,
    DeficiencyStatus,
    ControlSelfAssessment,
    CSAStatus,
    CCMRule,
    CCMRuleType,
    CCMExecution,
    CCMResult,
    GRCEvidence,
    EvidenceStatus,
    SignOffCertification,
    SignOffStatus,
    # GovernexPlus gap models
    ControlObjective,
    ObjectiveStatus as PCObjectiveStatus,
    SubProcess,
    PolicyDocument,
    PolicyType,
    PolicyStatus,
    QuestionLibrary,
    QuestionType,
    Questionnaire,
    QuestionnaireType,
    QuestionnaireResponse,
    ResponseStatus as PCResponseStatus,
)

# Audit Management Module (AM-01 through AM-32 + GovernexPlus gaps)
from .audit_management import (
    AuditableEntity,
    AuditableEntityType,
    AuditPlan,
    AuditPlanType,
    AuditPlanStatus,
    AuditEngagement,
    EngagementType,
    EngagementStatus,
    AuditWorkProgram,
    AuditProcedure,
    ProcedureStatus,
    AuditWorkpaper,
    WorkpaperReviewStatus,
    WorkpaperStatus,
    AuditFinding,
    FindingSeverity,
    FindingStatus,
    AuditManagementAction,
    ActionStatus,
    AuditorTimeEntry,
    AuditorResource,
    # GovernexPlus gap models
    AuditDimension,
    DimensionType,
    AuditAnnouncement,
    AnnouncementStatus,
)

# Extended Modules (JML, TPRM, Fraud, BCM, Whistleblower, Survey)
from .extended_modules import (
    # JML
    JmlPolicy,
    JmlEventType,
    JmlEventStatus,
    JmlEvent,
    # TPRM
    Vendor,
    VendorStatus,
    VendorAssessment,
    VendorAssessmentStatus,
    VendorRiskRating,
    VendorIssue,
    VendorIssueSeverity,
    VendorIssueStatus,
    VendorContract,
    VendorContractStatus,
    # Fraud Detection
    FraudRule,
    FraudRuleType,
    FraudAlert,
    FraudAlertStatus,
    FraudCase,
    FraudCaseSeverity,
    FraudCaseStatus,
    # BCM
    BiaRecord,
    BcmCriticality,
    BcmPlan,
    BcmPlanType,
    BcmPlanStatus,
    BcmTestExercise,
    BcmExerciseType,
    BcmExerciseOutcome,
    IncidentActivation,
    BcmActivationSeverity,
    BcmActivationStatus,
    # Whistleblower
    WhistleblowerCase,
    WhistleblowerCategory,
    WhistleblowerStatus,
    WhistleblowerPriority,
    WhistleblowerMessage,
    WhistleblowerSender,
    # Survey
    StandaloneSurvey,
    SurveyType,
    SurveyStatus,
    SurveyDistribution,
    SurveyDistributionStatus,
    SurveyAnswer,
)

__all__ = [
    # Core
    "Base",
    "Tenant",
    "TenantStatus",
    "TenantTier",
    "User",
    "Role",
    "UserRole",
    "UserEntitlement",
    "RiskViolation",
    "MitigationControl",
    "RiskRuleModel",
    "TenantRulePreference",
    "FirefighterRequest",
    "FirefighterSession",
    "FirefighterActivity",
    "FirefighterIDConfig",
    "AuditLog",
    "AccessRequestLog",
    "CertificationCampaignLog",
    "CertificationItemLog",
    "AdminSession",
    "ApproverModel",
    "ApprovalRuleModel",
    "SAPSecurityControl",
    "ControlValueMapping",
    "ControlEvaluation",
    "ControlException",
    "SystemSecurityProfile",
    "RiskRating",
    "ControlCategory",
    "ControlStatus",
    "EvaluationStatus",
    "OrgRule",
    "OrgUserAssignment",
    "OrgRoleRestriction",
    "BulkJob",
    "SyncConfig",
    "SyncHistory",
    "TransportRecord",
    "NotificationRecord",
    "NotificationPreference",
    "CustomTcodeRecord",
    "ModelTemplate",
    "MitigationMonitorRecord",
    "OrchestrationContextRecord",
    "TroubleshooterKBUser",
    "TroubleshooterKBRole",
    "TroubleshooterKBTransaction",
    "RoleIntelligenceRecord",
    "DriftSnapshot",
    "FioriAppRecord",
    "IdentityAccount",
    "IdentityClusterRecord",
    "MigrationMapping",
    "TimelineEvent",
    "AuditEvidenceItem",
    "EvidenceRecordDB",
    "FindingRecordDB",
    "ExecutionPlanRecord",
    "DecisionWorkflowRecord",
    "ShoppingCartModel",
    # GRC Foundation
    "OrgUnit",
    "OrgUnitType",
    "FrameworkDefinition",
    "FrameworkType",
    "FrameworkRequirement",
    # Risk Management
    "EnterpriseRisk",
    "RiskCategory",
    "RiskStatus",
    "RiskAssessment",
    "AssessmentType",
    "AssessmentStatus",
    "RiskAppetite",
    "KeyRiskIndicator",
    "KRIStatus",
    "KRIMeasurement",
    "RiskResponse",
    "RiskResponseType",
    "ResponseStatus",
    "RiskIncident",
    "IncidentSeverity",
    "IncidentStatus",
    # Risk Management — GovernexPlus gaps
    "BusinessObjective",
    "ObjectiveCategory",
    "ObjectiveStatus",
    "RiskScenario",
    "ScenarioType",
    "ScenarioVelocity",
    "ScenarioStatus",
    "MonteCarloSimulation",
    "DistributionType",
    "RiskOpportunity",
    "OpportunityCategory",
    "OpportunityStatus",
    # Process Control
    "ProcessControl",
    "ControlType",
    "ControlNature",
    "ControlFrequency",
    "ControlTest",
    "TestType",
    "TestResult",
    "TestStatus",
    "ControlDeficiency",
    "DeficiencySeverity",
    "DeficiencyStatus",
    "ControlSelfAssessment",
    "CSAStatus",
    "CCMRule",
    "CCMRuleType",
    "CCMExecution",
    "CCMResult",
    "GRCEvidence",
    "EvidenceStatus",
    "SignOffCertification",
    "SignOffStatus",
    # Process Control — GovernexPlus gaps
    "ControlObjective",
    "PCObjectiveStatus",
    "SubProcess",
    "PolicyDocument",
    "PolicyType",
    "PolicyStatus",
    "QuestionLibrary",
    "QuestionType",
    "Questionnaire",
    "QuestionnaireType",
    "QuestionnaireResponse",
    "PCResponseStatus",
    # Audit Management
    "AuditableEntity",
    "AuditableEntityType",
    "AuditPlan",
    "AuditPlanType",
    "AuditPlanStatus",
    "AuditEngagement",
    "EngagementType",
    "EngagementStatus",
    "AuditWorkProgram",
    "AuditProcedure",
    "ProcedureStatus",
    "AuditWorkpaper",
    "WorkpaperReviewStatus",
    "WorkpaperStatus",
    "AuditFinding",
    "FindingSeverity",
    "FindingStatus",
    "AuditManagementAction",
    "ActionStatus",
    "AuditorTimeEntry",
    "AuditorResource",
    # Audit Management — GovernexPlus gaps
    "AuditDimension",
    "DimensionType",
    "AuditAnnouncement",
    "AnnouncementStatus",
    # Extended Modules — JML
    "JmlPolicy",
    "JmlEventType",
    "JmlEventStatus",
    "JmlEvent",
    # Extended Modules — TPRM
    "Vendor",
    "VendorStatus",
    "VendorAssessment",
    "VendorAssessmentStatus",
    "VendorRiskRating",
    "VendorIssue",
    "VendorIssueSeverity",
    "VendorIssueStatus",
    "VendorContract",
    "VendorContractStatus",
    # Extended Modules — Fraud Detection
    "FraudRule",
    "FraudRuleType",
    "FraudAlert",
    "FraudAlertStatus",
    "FraudCase",
    "FraudCaseSeverity",
    "FraudCaseStatus",
    # Extended Modules — BCM
    "BiaRecord",
    "BcmCriticality",
    "BcmPlan",
    "BcmPlanType",
    "BcmPlanStatus",
    "BcmTestExercise",
    "BcmExerciseType",
    "BcmExerciseOutcome",
    "IncidentActivation",
    "BcmActivationSeverity",
    "BcmActivationStatus",
    # Extended Modules — Whistleblower
    "WhistleblowerCase",
    "WhistleblowerCategory",
    "WhistleblowerStatus",
    "WhistleblowerPriority",
    "WhistleblowerMessage",
    "WhistleblowerSender",
    # Extended Modules — Survey
    "StandaloneSurvey",
    "SurveyType",
    "SurveyStatus",
    "SurveyDistribution",
    "SurveyDistributionStatus",
    "SurveyAnswer",
]
