"""add_engine_persistence_tables

Revision ID: abd0e2efd983
Revises: 508dbe6ec160
Create Date: 2026-08-22 18:39:56.420840+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd0e2efd983'
down_revision: Union[str, None] = '508dbe6ec160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_sessions',
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('logged_in_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('certification_campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('campaign_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.String(length=50), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('included_systems', sa.JSON(), nullable=True),
    sa.Column('included_departments', sa.JSON(), nullable=True),
    sa.Column('risk_threshold', sa.Integer(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('completed_items', sa.Integer(), nullable=True),
    sa.Column('certified_count', sa.Integer(), nullable=True),
    sa.Column('revoked_count', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certification_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certification_campaigns_campaign_id'), ['campaign_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_certification_campaigns_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('certification_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('campaign_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_department', sa.String(length=100), nullable=True),
    sa.Column('access_type', sa.String(length=50), nullable=True),
    sa.Column('access_id', sa.String(length=100), nullable=False),
    sa.Column('access_name', sa.String(length=255), nullable=True),
    sa.Column('system', sa.String(length=50), nullable=True),
    sa.Column('granted_date', sa.DateTime(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('has_sod_violation', sa.Boolean(), nullable=True),
    sa.Column('risk_flags', sa.JSON(), nullable=True),
    sa.Column('reviewer_id', sa.String(length=50), nullable=False),
    sa.Column('reviewer_name', sa.String(length=255), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('decision_date', sa.DateTime(), nullable=True),
    sa.Column('decision_comments', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=True),
    sa.Column('is_overdue', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certification_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certification_items_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certification_items_item_id'), ['item_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_certification_items_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certification_items_user_id'), ['user_id'], unique=False)

    op.create_table('engine_decision_workflows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.String(length=100), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('request_type', sa.String(length=50), nullable=True),
    sa.Column('policy_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('final_decision', sa.String(length=20), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('sod_violations_count', sa.Integer(), nullable=True),
    sa.Column('new_violations_count', sa.Integer(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_decision_workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_decision_workflows_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_decision_workflows_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_decision_workflows_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_decision_workflows_workflow_id'), ['workflow_id'], unique=True)

    op.create_table('engine_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evidence_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('actor_user_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('target_user_id', sa.String(length=100), nullable=True),
    sa.Column('target_object_type', sa.String(length=100), nullable=True),
    sa.Column('target_object_id', sa.String(length=200), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('workflow_id', sa.String(length=100), nullable=True),
    sa.Column('finding_id', sa.String(length=100), nullable=True),
    sa.Column('plan_id', sa.String(length=100), nullable=True),
    sa.Column('campaign_id', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('action_details', sa.JSON(), nullable=True),
    sa.Column('system_response', sa.JSON(), nullable=True),
    sa.Column('previous_hash', sa.String(length=128), nullable=True),
    sa.Column('record_hash', sa.String(length=128), nullable=False),
    sa.Column('integrity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_evidence_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_evidence_evidence_id'), ['evidence_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_engine_evidence_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_evidence_target_user_id'), ['target_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_evidence_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('engine_execution_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.String(length=100), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('workflow_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('phase', sa.String(length=30), nullable=False),
    sa.Column('execution_mode', sa.String(length=20), nullable=True),
    sa.Column('executed_by', sa.String(length=100), nullable=True),
    sa.Column('pre_risk_score', sa.Float(), nullable=True),
    sa.Column('pre_violation_count', sa.Integer(), nullable=True),
    sa.Column('post_risk_score', sa.Float(), nullable=True),
    sa.Column('post_violation_count', sa.Integer(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('simulated_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_execution_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_execution_plans_plan_id'), ['plan_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_engine_execution_plans_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_execution_plans_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_execution_plans_user_id'), ['user_id'], unique=False)

    op.create_table('engine_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('finding_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('finding_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('system_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('business_impact', sa.String(length=50), nullable=True),
    sa.Column('sox_relevant', sa.Boolean(), nullable=True),
    sa.Column('rule_id', sa.String(length=100), nullable=True),
    sa.Column('violation_id', sa.String(length=100), nullable=True),
    sa.Column('campaign_id', sa.String(length=100), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('related_roles', sa.JSON(), nullable=True),
    sa.Column('related_transactions', sa.JSON(), nullable=True),
    sa.Column('related_auth_objects', sa.JSON(), nullable=True),
    sa.Column('org_scope', sa.JSON(), nullable=True),
    sa.Column('regulatory_refs', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_findings_finding_id'), ['finding_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_engine_findings_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_findings_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('access_request_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=100), nullable=False))
        batch_op.create_index(batch_op.f('ix_access_request_logs_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('firefighter_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=100), nullable=False))
        batch_op.create_index(batch_op.f('ix_firefighter_requests_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('firefighter_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=100), nullable=False))
        batch_op.create_index(batch_op.f('ix_firefighter_sessions_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firefighter_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firefighter_sessions_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('firefighter_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firefighter_requests_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('access_request_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_request_logs_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('engine_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_findings_user_id'))
        batch_op.drop_index(batch_op.f('ix_engine_findings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_engine_findings_finding_id'))

    op.drop_table('engine_findings')
    with op.batch_alter_table('engine_execution_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_execution_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_engine_execution_plans_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_engine_execution_plans_request_id'))
        batch_op.drop_index(batch_op.f('ix_engine_execution_plans_plan_id'))

    op.drop_table('engine_execution_plans')
    with op.batch_alter_table('engine_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_evidence_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_engine_evidence_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_engine_evidence_request_id'))
        batch_op.drop_index(batch_op.f('ix_engine_evidence_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_engine_evidence_actor_user_id'))

    op.drop_table('engine_evidence')
    with op.batch_alter_table('engine_decision_workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_decision_workflows_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_engine_decision_workflows_user_id'))
        batch_op.drop_index(batch_op.f('ix_engine_decision_workflows_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_engine_decision_workflows_request_id'))

    op.drop_table('engine_decision_workflows')
    with op.batch_alter_table('certification_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certification_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_certification_items_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_certification_items_item_id'))
        batch_op.drop_index(batch_op.f('ix_certification_items_campaign_id'))

    op.drop_table('certification_items')
    with op.batch_alter_table('certification_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certification_campaigns_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_certification_campaigns_campaign_id'))

    op.drop_table('certification_campaigns')
    op.drop_table('admin_sessions')
    # ### end Alembic commands ###
