"""
Mitigation Monitoring API Router

Endpoints for checking mitigation health, viewing expiring/expired controls,
triggering full health checks, and managing scheduled monitoring jobs.

XL-C additions (Unified Mitigation Register — Loop C):
  GET  /controls/{control_id}/backing-status  — backing PC control test + deficiency status
  GET  /unlinked-report                       — mitigations with no tested backing control
  PUT  /controls/{control_id}/link            — attach a process_control_id to a mitigation
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from core.mitigation.monitoring import get_monitor
from core.logging import get_logger
from db.database import get_db

logger = get_logger(__name__)
router = APIRouter(tags=["Mitigation Monitoring"])
_monitor = get_monitor()


# ---------------------------------------------------------------------------
# Tenant helper
# ---------------------------------------------------------------------------

def _get_tenant_id() -> str:
    from core.tenant import get_current_tenant
    ctx = get_current_tenant()
    return ctx.tenant_id if ctx else "default"


# ---------------------------------------------------------------------------
# Request models
# ---------------------------------------------------------------------------

class RunCheckRequest(BaseModel):
    days_ahead: int = Field(
        default=30,
        ge=1,
        le=180,
        description="Days of lookahead for expiry detection",
    )


class ScheduleRequest(BaseModel):
    interval_hours: int = Field(
        default=24,
        ge=1,
        le=168,
        description="How often (in hours) to run the full check. Max 168 (7 days).",
    )


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.get("/health")
async def get_health_dashboard() -> Dict[str, Any]:
    """
    Return the mitigation health dashboard.

    Provides a high-level overview: health score, counts of expiring /
    expired / ineffective controls, unassigned violations, and recent alerts.
    No new alerts are generated by this endpoint.
    """
    return _monitor.get_health_dashboard()


@router.get("/expiring")
async def get_expiring_mitigations(
    days_ahead: int = Query(
        default=30,
        ge=1,
        le=180,
        description="Days ahead to include in the expiry window",
    ),
) -> Dict[str, Any]:
    """
    List mitigation controls expiring within the specified number of days.

    Returns each control with a 'days_remaining' field.
    Results are ordered by days remaining (soonest first).
    """
    controls = _monitor.check_expiring_mitigations(days_ahead=days_ahead)
    controls.sort(key=lambda c: c.get("days_remaining") or 9999)
    return {
        "days_ahead": days_ahead,
        "total": len(controls),
        "controls": controls,
    }


@router.get("/expired")
async def get_expired_mitigations() -> Dict[str, Any]:
    """
    List all mitigation controls that have already expired.

    Returns each control with a 'days_overdue' field indicating how many
    days ago the control expired.
    """
    controls = _monitor.check_expired_mitigations()
    controls.sort(key=lambda c: c.get("days_overdue") or 0, reverse=True)
    return {
        "total": len(controls),
        "controls": controls,
    }


@router.get("/unassigned")
async def get_unassigned_violations() -> Dict[str, Any]:
    """
    List SoD/risk violations that have no mitigation control assigned.

    Results are ordered by risk severity (critical first).
    These violations represent unacceptable open risks.
    """
    violations = _monitor.check_unassigned_violations()
    return {
        "total": len(violations),
        "violations": violations,
    }


@router.get("/ineffective")
async def get_ineffective_controls() -> Dict[str, Any]:
    """
    List active controls whose effectiveness score is below the threshold (50%).

    Returns each control with an 'effectiveness_gap' showing how far below the
    threshold the score is.
    """
    controls = _monitor.check_control_effectiveness()
    return {
        "total": len(controls),
        "threshold": _monitor.INEFFECTIVE_THRESHOLD,
        "controls": controls,
    }


@router.post("/run-check")
async def run_full_check(req: RunCheckRequest) -> Dict[str, Any]:
    """
    Execute a full mitigation health check immediately.

    Runs all four checks (expiring, expired, unassigned, ineffective),
    generates alerts, and returns a complete MitigationHealthReport.
    """
    report = _monitor.run_full_check(days_ahead=req.days_ahead)
    logger.info(
        "api.full_check_run",
        alerts_generated=report.alerts_generated,
        days_ahead=req.days_ahead,
    )
    return report.to_dict()


@router.get("/alerts")
async def get_alerts(
    alert_type: Optional[str] = Query(
        None,
        description="Filter by type: expiring, expired, unassigned_violation, ineffective_control",
    ),
    severity: Optional[str] = Query(
        None,
        description="Filter by severity: info, warning, critical",
    ),
    limit: int = Query(default=100, ge=1, le=500),
) -> Dict[str, Any]:
    """
    Return the history of alerts generated by past monitoring runs.

    Supports optional filtering by alert type and severity.
    Returns most recent alerts first.
    """
    # Validate optional enum values
    valid_types = {"expiring", "expired", "unassigned_violation", "ineffective_control"}
    valid_severities = {"info", "warning", "critical"}

    if alert_type and alert_type not in valid_types:
        raise HTTPException(
            status_code=422,
            detail=f"Invalid alert_type '{alert_type}'. Valid: {sorted(valid_types)}",
        )
    if severity and severity not in valid_severities:
        raise HTTPException(
            status_code=422,
            detail=f"Invalid severity '{severity}'. Valid: {sorted(valid_severities)}",
        )

    alerts = _monitor.get_alert_history(
        alert_type=alert_type,
        severity=severity,
        limit=limit,
    )
    return {
        "total": len(alerts),
        "filters": {"alert_type": alert_type, "severity": severity},
        "alerts": alerts,
    }


@router.post("/schedule")
async def schedule_check(req: ScheduleRequest) -> Dict[str, Any]:
    """
    Start (or restart) the background monitoring scheduler.

    The scheduler runs run_full_check() at the specified interval.
    Calling this endpoint while a scheduler is already running will
    stop the previous one and start a new one with the new interval.
    """
    result = _monitor.schedule_check(interval_hours=req.interval_hours)
    logger.info("api.scheduler_started", interval_hours=req.interval_hours)
    return {
        "message": "Mitigation monitoring scheduler started",
        **result,
    }


# ===========================================================================
# XL-C — Unified Mitigation Register (Loop C)
# ===========================================================================

class LinkBackingControlRequest(BaseModel):
    process_control_id: str = Field(
        ...,
        description="The control_id (business key) of the ProcessControl in the PC module",
    )


@router.get("/controls/{control_id}/backing-status")
def get_backing_status(
    control_id: str,
    db: Session = Depends(get_db),
    tenant_id: str = Depends(_get_tenant_id),
) -> Dict[str, Any]:
    """
    XL-C — Backing control status for a mitigation.

    Looks up the MitigationControl whose control_id matches *control_id*,
    then follows its process_control_id foreign key into the PC module to
    retrieve:
      - The latest ControlTest result and date
      - Count of open ControlDeficiency records (open + in_remediation)
      - The backing ProcessControl name, status, and key_control flag

    If no process_control_id is set on the mitigation, the response
    indicates the control is unlinked.
    """
    from db.models.risk import MitigationControl
    from db.models.process_control import (
        ProcessControl, ControlTest, ControlDeficiency,
        DeficiencyStatus, TestResult,
    )

    mitigation = db.query(MitigationControl).filter(
        MitigationControl.tenant_id == tenant_id,
        MitigationControl.control_id == control_id,
        MitigationControl.is_active == True,  # noqa: E712
    ).first()

    if not mitigation:
        raise HTTPException(
            status_code=404,
            detail=f"Mitigation control '{control_id}' not found",
        )

    base = mitigation.to_dict()

    if not mitigation.process_control_id:
        return {
            **base,
            "backing_control_linked": False,
            "backing_control": None,
            "latest_test_result": None,
            "latest_test_date": None,
            "open_deficiency_count": 0,
            "material_weakness_count": 0,
        }

    pc = db.query(ProcessControl).filter(
        ProcessControl.tenant_id == tenant_id,
        ProcessControl.control_id == mitigation.process_control_id,
        ProcessControl.is_active == True,  # noqa: E712
    ).first()

    if not pc:
        return {
            **base,
            "backing_control_linked": True,
            "backing_control": None,
            "backing_control_missing": True,
            "latest_test_result": None,
            "latest_test_date": None,
            "open_deficiency_count": 0,
            "material_weakness_count": 0,
        }

    # Latest test result
    latest_test = (
        db.query(ControlTest)
        .filter(
            ControlTest.tenant_id == tenant_id,
            ControlTest.control_id == pc.id,
        )
        .order_by(ControlTest.created_at.desc())
        .first()
    )

    # Open deficiency counts
    open_defs = db.query(ControlDeficiency).filter(
        ControlDeficiency.tenant_id == tenant_id,
        ControlDeficiency.control_id == pc.id,
        ControlDeficiency.status.in_([
            DeficiencyStatus.OPEN,
            DeficiencyStatus.IN_REMEDIATION,
        ]),
    ).all()

    from db.models.process_control import DeficiencySeverity
    material_weakness_count = sum(
        1 for d in open_defs if d.severity == DeficiencySeverity.MATERIAL_WEAKNESS
    )

    return {
        **base,
        "backing_control_linked": True,
        "backing_control": {
            "control_id": pc.control_id,
            "name": pc.name,
            "status": pc.status.value if pc.status else None,
            "key_control": pc.key_control,
            "frequency": pc.frequency.value if pc.frequency else None,
            "owner_name": pc.owner_name,
        },
        "latest_test_result": latest_test.result.value if latest_test and latest_test.result else None,
        "latest_test_date": latest_test.created_at.isoformat() if latest_test and latest_test.created_at else None,
        "open_deficiency_count": len(open_defs),
        "material_weakness_count": material_weakness_count,
    }


@router.get("/unlinked-report")
def get_unlinked_report(
    db: Session = Depends(get_db),
    tenant_id: str = Depends(_get_tenant_id),
) -> Dict[str, Any]:
    """
    XL-C — Unified Register Gap Report (sales-demo query).

    Returns all active mitigation controls that fall into one of two gap
    categories, demonstrating the value of a unified AC+PC register:

    1. **Unlinked** — no process_control_id is set; the mitigation has no
       backing internal control and therefore receives no testing, sign-off,
       or framework coverage from the PC module.

    2. **Ineffective backing** — a process_control_id is set, but the linked
       ProcessControl's most recent ControlTest result is 'ineffective'; the
       mitigation's asserted coverage is contradicted by audit evidence.

    Each result includes:
      gap_reason   : 'no_backing_control' | 'ineffective_backing_test'
      control_id   : MitigationControl business key
      control_name : human-readable name
      process_control_id : the PC control ID (None when unlinked)
      latest_test_result : the PC test result (None when unlinked)
      latest_test_date   : ISO timestamp of the last test
    """
    from db.models.risk import MitigationControl
    from db.models.process_control import ProcessControl, ControlTest, TestResult

    mitigations = db.query(MitigationControl).filter(
        MitigationControl.tenant_id == tenant_id,
        MitigationControl.is_active == True,  # noqa: E712
    ).all()

    gaps: List[Dict[str, Any]] = []

    for m in mitigations:
        if not m.process_control_id:
            # Gap type 1: no backing control at all
            gaps.append({
                "gap_reason": "no_backing_control",
                "control_id": m.control_id,
                "control_name": m.control_name,
                "control_type": m.control_type,
                "owner_name": m.owner_name,
                "process_control_id": None,
                "latest_test_result": None,
                "latest_test_date": None,
                "valid_to": m.valid_to.isoformat() if m.valid_to else None,
            })
            continue

        # Gap type 2: backing control exists — check latest test
        pc = db.query(ProcessControl).filter(
            ProcessControl.tenant_id == tenant_id,
            ProcessControl.control_id == m.process_control_id,
            ProcessControl.is_active == True,  # noqa: E712
        ).first()

        if not pc:
            # Linked control_id no longer exists in PC — treat as unlinked
            gaps.append({
                "gap_reason": "no_backing_control",
                "control_id": m.control_id,
                "control_name": m.control_name,
                "control_type": m.control_type,
                "owner_name": m.owner_name,
                "process_control_id": m.process_control_id,
                "backing_control_missing": True,
                "latest_test_result": None,
                "latest_test_date": None,
                "valid_to": m.valid_to.isoformat() if m.valid_to else None,
            })
            continue

        latest_test = (
            db.query(ControlTest)
            .filter(
                ControlTest.tenant_id == tenant_id,
                ControlTest.control_id == pc.id,
            )
            .order_by(ControlTest.created_at.desc())
            .first()
        )

        if latest_test and latest_test.result == TestResult.INEFFECTIVE:
            gaps.append({
                "gap_reason": "ineffective_backing_test",
                "control_id": m.control_id,
                "control_name": m.control_name,
                "control_type": m.control_type,
                "owner_name": m.owner_name,
                "process_control_id": m.process_control_id,
                "backing_control_name": pc.name,
                "latest_test_result": latest_test.result.value,
                "latest_test_date": latest_test.created_at.isoformat() if latest_test.created_at else None,
                "valid_to": m.valid_to.isoformat() if m.valid_to else None,
            })

    no_backing = sum(1 for g in gaps if g["gap_reason"] == "no_backing_control")
    ineffective = sum(1 for g in gaps if g["gap_reason"] == "ineffective_backing_test")

    return {
        "generated_at": __import__("datetime").datetime.utcnow().isoformat(),
        "total_active_mitigations": len(mitigations),
        "total_gaps": len(gaps),
        "summary": {
            "no_backing_control": no_backing,
            "ineffective_backing_test": ineffective,
        },
        "gaps": gaps,
    }


@router.put("/controls/{control_id}/link")
def link_backing_control(
    control_id: str,
    body: LinkBackingControlRequest,
    db: Session = Depends(get_db),
    tenant_id: str = Depends(_get_tenant_id),
) -> Dict[str, Any]:
    """
    XL-C — Link a MitigationControl to its backing ProcessControl.

    Sets process_control_id on the MitigationControl identified by *control_id*.
    The backing control is validated to exist and be active in this tenant.

    After linking, call GET /controls/{control_id}/backing-status to see the
    full PC test and deficiency picture for this mitigation.
    """
    from db.models.risk import MitigationControl
    from db.models.process_control import ProcessControl

    mitigation = db.query(MitigationControl).filter(
        MitigationControl.tenant_id == tenant_id,
        MitigationControl.control_id == control_id,
        MitigationControl.is_active == True,  # noqa: E712
    ).first()

    if not mitigation:
        raise HTTPException(
            status_code=404,
            detail=f"Mitigation control '{control_id}' not found",
        )

    # Validate that the target ProcessControl exists in this tenant
    pc = db.query(ProcessControl).filter(
        ProcessControl.tenant_id == tenant_id,
        ProcessControl.control_id == body.process_control_id,
        ProcessControl.is_active == True,  # noqa: E712
    ).first()

    if not pc:
        raise HTTPException(
            status_code=404,
            detail=(
                f"ProcessControl '{body.process_control_id}' not found or inactive "
                f"for this tenant. Create it in the Process Control module first."
            ),
        )

    previous_id = mitigation.process_control_id
    mitigation.process_control_id = body.process_control_id
    db.commit()

    logger.info(
        "xlc.link_backing_control",
        mitigation_id=control_id,
        process_control_id=body.process_control_id,
        previous_id=previous_id,
        tenant_id=tenant_id,
    )

    return {
        "control_id": control_id,
        "process_control_id": body.process_control_id,
        "backing_control_name": pc.name,
        "previously_linked_to": previous_id,
        "linked_at": __import__("datetime").datetime.utcnow().isoformat(),
        "message": (
            f"Mitigation '{control_id}' is now backed by ProcessControl "
            f"'{body.process_control_id}' ({pc.name}). "
            "Call GET /controls/{control_id}/backing-status for full coverage details."
        ),
    }
