#!/usr/bin/env python3
"""Seed control library hierarchy for GvnX tenant."""
import paramiko
import uuid

T = "gvnx"
lines = []

def rid():
    return uuid.uuid4().hex[:12]

# Subprocesses
subprocess_data = {
    "Record to Report": ["General Ledger","Account Reconciliation","Period-End Close","Financial Reporting","Foreign Currency","Intercompany","Consolidation"],
    "Procure to Pay": ["Purchase Requisition","Sourcing","Purchase Order","Goods Receipt","Invoice Processing","Payment Processing","Vendor Management"],
    "Order to Cash": ["Customer Management","Credit Management","Sales Order","Delivery","Billing","Accounts Receivable","Returns","Revenue Recognition"],
    "Hire to Retire": ["Hiring","Employee Master Data","Compensation","Payroll","Time Management","Termination"],
    "Acquire to Retire": ["Acquisition","Capitalization","Asset Master","Depreciation","Physical Verification","Disposal","Reconciliation"],
    "Plan to Produce": ["Production Planning","BOM and Routing","Production Order","Production Execution","WIP","Costing","Variance"],
    "Inventory Management": ["Physical Inventory","Goods Movement","Stock Transfer","Warehouse Operations","Scrap","Valuation"],
    "Treasury and Cash": ["Bank Management","Cash Management","Payment Processing","Foreign Exchange","Reconciliation"],
    "Tax Management": ["Tax Master Data","Input and Output Tax","GST and VAT","Tax Returns"],
    "Master Data Management": ["Vendor Master","Customer Master","Material Master","GL Account Master","Cost Center"],
    "Project Management": ["Project Creation","Budget Management","Cost Monitoring","Settlement"],
    "Quality Management": ["Inspection","Quality Control","Nonconformance"],
    "Plant Maintenance": ["Maintenance Order","Preventive Maintenance","Costs"],
    "Intercompany": ["IC Transactions","IC Balances","Elimination","Consolidation Data"],
    "IT General Controls": ["User Access","Segregation of Duties","Change Management","Configuration","Operations","Backup and Recovery","Security"],
    "Interfaces and Data": ["Interface Completeness","Interface Accuracy","Interface Failures","Data Monitoring"],
    "Compliance": ["SOX Compliance","Regulatory","Anti-Fraud","Privacy","Certification"],
}

for proc, sl in subprocess_data.items():
    for i, s in enumerate(sl):
        lines.append(f"INSERT INTO subprocesses (tenant_id,subprocess_id,name,process_name,level,sort_order,is_active,created_at,updated_at) VALUES ('{T}','SP-{rid()}','{s}','{proc}',1,{i+1},true,NOW(),NOW());")

# Objectives
for proc, sub, title in [
    ("Record to Report","General Ledger","Accurate journal postings"),
    ("Record to Report","Account Reconciliation","Complete reconciliation"),
    ("Record to Report","Period-End Close","Timely close"),
    ("Procure to Pay","Invoice Processing","Accurate invoices"),
    ("Procure to Pay","Payment Processing","Valid payments"),
    ("Order to Cash","Sales Order","Authorized sales"),
    ("Order to Cash","Billing","Accurate billing"),
    ("Hire to Retire","Payroll","Accurate payroll"),
    ("IT General Controls","User Access","Authorized access"),
    ("IT General Controls","Change Management","Controlled changes"),
]:
    lines.append(f"INSERT INTO control_objectives (tenant_id,objective_id,title,description,process_name,subprocess_name,status,is_active,created_at,updated_at) VALUES ('{T}','OBJ-{rid()}','{title}','Ensure {title.lower()}','{proc}','{sub}','active',true,NOW(),NOW());")

lines.append(f"DELETE FROM control_tests WHERE tenant_id='{T}';")
lines.append(f"DELETE FROM process_controls WHERE tenant_id='{T}';")

# Control data: (id, subprocess, name, type, nature, frequency, process, owner, key_control)
controls = [
    # R2R (20)
    ("R2R-001","General Ledger","Manual journal entries require approval","preventive","manual","continuous","Record to Report","RAHUL00","true"),
    ("R2R-002","General Ledger","High-value journals additional approval","preventive","manual","continuous","Record to Report","RAHUL00","true"),
    ("R2R-003","General Ledger","Unauthorized journal postings detected","detective","automated","continuous","Record to Report","RAHUL00","true"),
    ("R2R-004","General Ledger","Weekend postings reviewed","detective","automated","daily","Record to Report","RAHUL00","false"),
    ("R2R-005","General Ledger","Backdated entries monitored","detective","automated","continuous","Record to Report","RAHUL00","false"),
    ("R2R-006","General Ledger","Round-amount journals reviewed","detective","automated","daily","Record to Report","RAHUL00","false"),
    ("R2R-007","General Ledger","Manual journal supporting docs","detective","manual","continuous","Record to Report","RAHUL00","true"),
    ("R2R-008","General Ledger","Suspense accounts reviewed","detective","manual","monthly","Record to Report","RAHUL00","false"),
    ("R2R-009","General Ledger","GL account creation approved","preventive","manual","continuous","Record to Report","RAHUL00","true"),
    ("R2R-010","Account Reconciliation","Bank-to-GL reconciliation","detective","manual","monthly","Record to Report","RAHUL00","true"),
    ("R2R-011","Account Reconciliation","Subledger reconciles to GL","detective","automated","monthly","Record to Report","RAHUL00","true"),
    ("R2R-012","Period-End Close","Close checklist completed","detective","manual","monthly","Record to Report","RAHUL00","true"),
    ("R2R-013","Period-End Close","Posting periods closed","preventive","automated","monthly","Record to Report","RAHUL00","true"),
    ("R2R-014","Period-End Close","Cut-off procedures performed","detective","manual","monthly","Record to Report","RAHUL00","true"),
    ("R2R-015","Period-End Close","Accruals reviewed","detective","manual","monthly","Record to Report","RAHUL00","true"),
    ("R2R-016","Financial Reporting","Financial statements reviewed","detective","manual","quarterly","Record to Report","RAHUL00","true"),
    ("R2R-017","Financial Reporting","Reporting adjustments approved","preventive","manual","quarterly","Record to Report","RAHUL00","true"),
    ("R2R-018","Intercompany","IC balances reconciled","detective","automated","monthly","Record to Report","RAHUL00","true"),
    ("R2R-019","Consolidation","Consolidation adjustments approved","preventive","manual","quarterly","Record to Report","RAHUL00","true"),
    ("R2R-020","Consolidation","Elimination entries reviewed","detective","manual","quarterly","Record to Report","RAHUL00","true"),
    # P2P (18)
    ("P2P-001","Purchase Requisition","PR requires approval","preventive","manual","continuous","Procure to Pay","VIKRA04","true"),
    ("P2P-002","Purchase Requisition","Budget availability checked","preventive","automated","continuous","Procure to Pay","VIKRA04","true"),
    ("P2P-003","Sourcing","Competitive bidding above threshold","preventive","manual","continuous","Procure to Pay","VIKRA04","true"),
    ("P2P-004","Purchase Order","PO requires approval","preventive","manual","continuous","Procure to Pay","VIKRA04","true"),
    ("P2P-005","Purchase Order","High-value POs additional approval","preventive","manual","continuous","Procure to Pay","VIKRA04","true"),
    ("P2P-006","Goods Receipt","GR requires authorized user","preventive","automated","continuous","Procure to Pay","VIKRA04","true"),
    ("P2P-007","Goods Receipt","GR quantity compared with PO","detective","automated","continuous","Procure to Pay","VIKRA04","false"),
    ("P2P-008","Invoice Processing","Three-way matching","preventive","automated","continuous","Procure to Pay","RAHUL00","true"),
    ("P2P-009","Invoice Processing","Duplicate invoices detected","detective","automated","continuous","Procure to Pay","RAHUL00","true"),
    ("P2P-010","Invoice Processing","Blocked invoices reviewed","detective","manual","weekly","Procure to Pay","RAHUL00","false"),
    ("P2P-011","Invoice Processing","Non-PO invoices require approval","preventive","manual","continuous","Procure to Pay","RAHUL00","true"),
    ("P2P-012","Payment Processing","Payment proposals reviewed","preventive","manual","continuous","Procure to Pay","RAHUL00","true"),
    ("P2P-013","Payment Processing","Payment batches approved","preventive","manual","continuous","Procure to Pay","RAHUL00","true"),
    ("P2P-014","Payment Processing","Dual approval high-value","preventive","manual","continuous","Procure to Pay","RAHUL00","true"),
    ("P2P-015","Payment Processing","Duplicate payments detected","detective","automated","continuous","Procure to Pay","RAHUL00","true"),
    ("P2P-016","Vendor Management","Vendor bank changes verified","preventive","manual","continuous","Procure to Pay","RAHUL00","true"),
    ("P2P-017","Vendor Management","Duplicate vendors identified","detective","automated","monthly","Procure to Pay","RAHUL00","true"),
    ("P2P-018","Vendor Management","Vendor master changes reviewed","detective","automated","daily","Procure to Pay","RAHUL00","false"),
    # O2C (12)
    ("O2C-001","Customer Management","Customer creation approved","preventive","manual","continuous","Order to Cash","ANJAL05","true"),
    ("O2C-002","Customer Management","Duplicate customers detected","detective","automated","continuous","Order to Cash","ANJAL05","true"),
    ("O2C-003","Credit Management","Credit limit approved","preventive","manual","continuous","Order to Cash","ANJAL05","true"),
    ("O2C-004","Sales Order","Orders require authorization","preventive","automated","continuous","Order to Cash","ANJAL05","true"),
    ("O2C-005","Sales Order","Orders above threshold approved","preventive","manual","continuous","Order to Cash","ANJAL05","true"),
    ("O2C-006","Delivery","Delivery requires valid order","preventive","automated","continuous","Order to Cash","ANJAL05","true"),
    ("O2C-007","Billing","Billing from valid delivery","preventive","automated","continuous","Order to Cash","ANJAL05","true"),
    ("O2C-008","Billing","Credit notes require approval","preventive","manual","continuous","Order to Cash","RAHUL00","true"),
    ("O2C-009","Accounts Receivable","AR reconciles with GL","detective","automated","monthly","Order to Cash","RAHUL00","true"),
    ("O2C-010","Accounts Receivable","Write-offs require approval","preventive","manual","continuous","Order to Cash","RAHUL00","true"),
    ("O2C-011","Revenue Recognition","Revenue recognition reviewed","detective","manual","monthly","Order to Cash","RAHUL00","true"),
    ("O2C-012","Returns","Return authorization required","preventive","manual","continuous","Order to Cash","ANJAL05","true"),
    # H2R (10)
    ("H2R-001","Hiring","New employee approved requisition","preventive","manual","continuous","Hire to Retire","SNEHA03","true"),
    ("H2R-002","Hiring","Employee master creation approved","preventive","manual","continuous","Hire to Retire","SNEHA03","true"),
    ("H2R-003","Hiring","Duplicate employees detected","detective","automated","continuous","Hire to Retire","SNEHA03","true"),
    ("H2R-004","Employee Master Data","Sensitive changes reviewed","detective","automated","daily","Hire to Retire","SNEHA03","true"),
    ("H2R-005","Compensation","Salary changes approved","preventive","manual","continuous","Hire to Retire","SNEHA03","true"),
    ("H2R-006","Payroll","Payroll run reviewed","detective","manual","monthly","Hire to Retire","SNEHA03","true"),
    ("H2R-007","Payroll","Payroll-to-GL reconciliation","detective","automated","monthly","Hire to Retire","SNEHA03","true"),
    ("H2R-008","Payroll","Ghost employees detected","detective","automated","quarterly","Hire to Retire","SNEHA03","true"),
    ("H2R-009","Termination","Termination approved","preventive","manual","continuous","Hire to Retire","SNEHA03","true"),
    ("H2R-010","Termination","Terminated access removed","preventive","automated","continuous","Hire to Retire","SNEHA03","true"),
    # A2R (6)
    ("A2R-001","Acquisition","Capital expenditure approved","preventive","manual","continuous","Acquire to Retire","RAHUL00","true"),
    ("A2R-002","Asset Master","Asset creation approved","preventive","manual","continuous","Acquire to Retire","RAHUL00","true"),
    ("A2R-003","Depreciation","Depreciation run reviewed","detective","manual","monthly","Acquire to Retire","RAHUL00","true"),
    ("A2R-004","Physical Verification","Physical asset verification","detective","manual","annual","Acquire to Retire","RAHUL00","true"),
    ("A2R-005","Disposal","Disposal approved","preventive","manual","continuous","Acquire to Retire","RAHUL00","true"),
    ("A2R-006","Reconciliation","Asset subledger reconciles GL","detective","automated","monthly","Acquire to Retire","RAHUL00","true"),
    # PP (6)
    ("PP-001","Production Planning","Production plan approved","preventive","manual","monthly","Plan to Produce","VIKRA04","true"),
    ("PP-002","BOM and Routing","BOM creation approved","preventive","manual","continuous","Plan to Produce","VIKRA04","true"),
    ("PP-003","Production Order","Production orders authorized","preventive","manual","continuous","Plan to Produce","VIKRA04","true"),
    ("PP-004","Production Execution","Material vs BOM compared","detective","automated","continuous","Plan to Produce","VIKRA04","true"),
    ("PP-005","WIP","WIP balances reconciled","detective","automated","monthly","Plan to Produce","VIKRA04","true"),
    ("PP-006","Costing","Standard cost changes approved","preventive","manual","continuous","Plan to Produce","VIKRA04","true"),
    # INV (5)
    ("INV-001","Physical Inventory","Physical counts performed","detective","manual","annual","Inventory Management","VIKRA04","true"),
    ("INV-002","Physical Inventory","Adjustments require approval","preventive","manual","continuous","Inventory Management","VIKRA04","true"),
    ("INV-003","Physical Inventory","Negative inventory monitored","detective","automated","continuous","Inventory Management","VIKRA04","true"),
    ("INV-004","Goods Movement","Movements require authorization","preventive","automated","continuous","Inventory Management","VIKRA04","true"),
    ("INV-005","Valuation","Inventory valuation reviewed","detective","manual","quarterly","Inventory Management","VIKRA04","true"),
    # TR (6)
    ("TR-001","Bank Management","Bank account creation approved","preventive","manual","continuous","Treasury and Cash","RAHUL00","true"),
    ("TR-002","Bank Management","Bank changes verified","preventive","manual","continuous","Treasury and Cash","RAHUL00","true"),
    ("TR-003","Bank Management","Bank reconciliation performed","detective","manual","monthly","Treasury and Cash","RAHUL00","true"),
    ("TR-004","Payment Processing","Payment batches approved","preventive","manual","continuous","Treasury and Cash","RAHUL00","true"),
    ("TR-005","Payment Processing","Dual auth high-value payments","preventive","manual","continuous","Treasury and Cash","RAHUL00","true"),
    ("TR-006","Payment Processing","Duplicate payments detected","detective","automated","continuous","Treasury and Cash","RAHUL00","true"),
    # TAX (4)
    ("TAX-001","Tax Master Data","Tax codes controlled creation","preventive","manual","continuous","Tax Management","RAHUL00","true"),
    ("TAX-002","Input and Output Tax","Input tax validated","detective","automated","continuous","Tax Management","RAHUL00","true"),
    ("TAX-003","GST and VAT","GST returns reconciled","detective","manual","monthly","Tax Management","RAHUL00","true"),
    ("TAX-004","Tax Returns","Tax return reviewed","detective","manual","monthly","Tax Management","RAHUL00","true"),
    # MD (6)
    ("MD-001","Vendor Master","New vendor approved","preventive","manual","continuous","Master Data Management","RAHUL00","true"),
    ("MD-002","Vendor Master","Vendor bank changes verified","preventive","manual","continuous","Master Data Management","RAHUL00","true"),
    ("MD-003","Vendor Master","Duplicate vendors detected","detective","automated","continuous","Master Data Management","RAHUL00","true"),
    ("MD-004","Customer Master","Customer creation approved","preventive","manual","continuous","Master Data Management","ANJAL05","true"),
    ("MD-005","Material Master","Material creation approved","preventive","manual","continuous","Master Data Management","VIKRA04","true"),
    ("MD-006","GL Account Master","GL creation approved","preventive","manual","continuous","Master Data Management","RAHUL00","true"),
    # PS (3)
    ("PS-001","Project Creation","Project creation approved","preventive","manual","continuous","Project Management","RAHUL00","true"),
    ("PS-002","Budget Management","Project budget approved","preventive","manual","continuous","Project Management","RAHUL00","true"),
    ("PS-003","Cost Monitoring","Costs vs budget compared","detective","automated","monthly","Project Management","RAHUL00","true"),
    # QM (3)
    ("QM-001","Inspection","Inspection lots created","preventive","automated","continuous","Quality Management","VIKRA04","true"),
    ("QM-002","Quality Control","Failed inspections prevent release","preventive","automated","continuous","Quality Management","VIKRA04","true"),
    ("QM-003","Nonconformance","Corrective action required","detective","manual","continuous","Quality Management","VIKRA04","true"),
    # PM (2)
    ("PM-001","Maintenance Order","Orders require approval","preventive","manual","continuous","Plant Maintenance","AMIT002","true"),
    ("PM-002","Preventive Maintenance","PM schedule monitored","detective","automated","continuous","Plant Maintenance","AMIT002","true"),
    # IC (3)
    ("IC-001","IC Transactions","IC transactions matched","detective","automated","monthly","Intercompany","RAHUL00","true"),
    ("IC-002","IC Balances","IC balances reconciled","detective","automated","monthly","Intercompany","RAHUL00","true"),
    ("IC-003","Elimination","Elimination entries approved","preventive","manual","quarterly","Intercompany","RAHUL00","true"),
    # ITGC (17)
    ("ITGC-001","User Access","New user requires approval","preventive","manual","continuous","IT General Controls","AMIT002","true"),
    ("ITGC-002","User Access","Role assignment approved","preventive","manual","continuous","IT General Controls","AMIT002","true"),
    ("ITGC-003","User Access","Privileged access additional approval","preventive","manual","continuous","IT General Controls","AMIT002","true"),
    ("ITGC-004","User Access","Periodic access certification","detective","manual","quarterly","IT General Controls","AMIT002","true"),
    ("ITGC-005","User Access","Terminated access removed","preventive","automated","continuous","IT General Controls","AMIT002","true"),
    ("ITGC-006","User Access","Inactive users disabled","detective","automated","monthly","IT General Controls","AMIT002","true"),
    ("ITGC-007","User Access","Emergency access logged and reviewed","detective","automated","continuous","IT General Controls","AMIT002","true"),
    ("ITGC-008","Segregation of Duties","SoD conflicts identified","detective","automated","continuous","IT General Controls","PRIYA01","true"),
    ("ITGC-009","Segregation of Duties","Critical access blocked","preventive","automated","continuous","IT General Controls","PRIYA01","true"),
    ("ITGC-010","Change Management","Production changes approved","preventive","manual","continuous","IT General Controls","AMIT002","true"),
    ("ITGC-011","Change Management","Emergency changes reviewed","detective","manual","continuous","IT General Controls","AMIT002","true"),
    ("ITGC-012","Change Management","Developer production access restricted","preventive","automated","continuous","IT General Controls","AMIT002","true"),
    ("ITGC-013","Configuration","Critical config changes monitored","detective","automated","continuous","IT General Controls","AMIT002","true"),
    ("ITGC-014","Backup and Recovery","Backups monitored","detective","automated","daily","IT General Controls","AMIT002","true"),
    ("ITGC-015","Backup and Recovery","Restore tested","detective","manual","quarterly","IT General Controls","AMIT002","true"),
    ("ITGC-016","Security","Security events monitored","detective","automated","continuous","IT General Controls","DEEPA09","true"),
    ("ITGC-017","Security","Security patches reviewed","detective","manual","monthly","IT General Controls","DEEPA09","true"),
    # INT (4)
    ("INT-001","Interface Completeness","Completeness validated","detective","automated","daily","Interfaces and Data","AMIT002","true"),
    ("INT-002","Interface Accuracy","Totals reconciled","detective","automated","daily","Interfaces and Data","AMIT002","true"),
    ("INT-003","Interface Failures","Failed interfaces identified","detective","automated","continuous","Interfaces and Data","AMIT002","true"),
    ("INT-004","Data Monitoring","Critical data changes logged","detective","automated","continuous","Interfaces and Data","AMIT002","true"),
    # COMP (6)
    ("COMP-001","SOX Compliance","Key controls identified","preventive","manual","annual","Compliance","SURES08","true"),
    ("COMP-002","SOX Compliance","Key controls tested","detective","manual","quarterly","Compliance","SURES08","true"),
    ("COMP-003","Anti-Fraud","Fraud indicators monitored","detective","automated","continuous","Compliance","SURES08","true"),
    ("COMP-004","Privacy","Personal data access monitored","detective","automated","continuous","Compliance","DEEPA09","true"),
    ("COMP-005","Certification","Control owners certify","detective","manual","quarterly","Compliance","SURES08","true"),
    ("COMP-006","Certification","Management certification completed","detective","manual","annual","Compliance","PRASANT","true"),
    # ── EXPANDED: R2R additional (15 more → 35 total) ──
    ("R2R-021","Close","Provisions reviewed and approved","detective","manual","monthly","Record to Report","RAHUL00","false"),
    ("R2R-022","Reporting","Reporting anomalies investigated","detective","automated","monthly","Record to Report","RAHUL00","false"),
    ("R2R-023","Master Data","GL account changes reviewed","detective","automated","daily","Record to Report","RAHUL00","false"),
    ("R2R-024","Master Data","Inactive GL accounts reviewed","detective","manual","quarterly","Record to Report","RAHUL00","false"),
    ("R2R-025","Foreign Currency","FX differences analyzed","detective","automated","monthly","Record to Report","RAHUL00","false"),
    ("R2R-026","Intercompany","Unmatched IC transactions investigated","detective","automated","monthly","Record to Report","RAHUL00","false"),
    ("R2R-027","GL","Reversal journals independently reviewed","detective","manual","weekly","Record to Report","RAHUL00","false"),
    ("R2R-028","Reconciliation","Old reconciling items escalated","detective","automated","monthly","Record to Report","RAHUL00","false"),
    ("R2R-029","Reconciliation","Balance-sheet accounts have assigned owners","preventive","manual","quarterly","Record to Report","RAHUL00","true"),
    ("R2R-030","Close","Late postings after close reviewed","detective","automated","monthly","Record to Report","RAHUL00","false"),
    ("R2R-031","Reporting","Trial balance reviewed","detective","manual","monthly","Record to Report","RAHUL00","true"),
    ("R2R-032","GL","Unusual round-amount journals reviewed","detective","automated","daily","Record to Report","RAHUL00","false"),
    ("R2R-033","GL","Weekend holiday postings reviewed","detective","automated","daily","Record to Report","RAHUL00","false"),
    ("R2R-034","Consolidation","Consolidated results management approval","detective","manual","quarterly","Record to Report","RAHUL00","true"),
    ("R2R-035","Close","Posting periods closed after activities","preventive","automated","monthly","Record to Report","RAHUL00","true"),
    # ── EXPANDED: P2P additional (17 more → 35 total) ──
    ("P2P-019","Sourcing","Supplier selection documented","detective","manual","continuous","Procure to Pay","VIKRA04","false"),
    ("P2P-020","PO","PO changes after approval reviewed","detective","automated","daily","Procure to Pay","VIKRA04","false"),
    ("P2P-021","PO","Purchases outside contract detected","detective","automated","daily","Procure to Pay","VIKRA04","false"),
    ("P2P-022","PO","Price variance against contract monitored","detective","automated","daily","Procure to Pay","VIKRA04","false"),
    ("P2P-023","PO","Unauthorized PO creation detected","detective","automated","continuous","Procure to Pay","VIKRA04","false"),
    ("P2P-024","Goods Receipt","GR without valid PO reviewed","detective","automated","daily","Procure to Pay","VIKRA04","false"),
    ("P2P-025","Goods Receipt","Excess receipts detected","detective","automated","continuous","Procure to Pay","VIKRA04","false"),
    ("P2P-026","Invoice","Invoice price variance reviewed","detective","automated","daily","Procure to Pay","RAHUL00","false"),
    ("P2P-027","Invoice","Invoice quantity variance reviewed","detective","automated","daily","Procure to Pay","RAHUL00","false"),
    ("P2P-028","Invoice","Vendor invoice tax validated","detective","automated","continuous","Procure to Pay","RAHUL00","false"),
    ("P2P-029","Payment","Payments to blocked vendors prevented","preventive","automated","continuous","Procure to Pay","RAHUL00","true"),
    ("P2P-030","Payment","Manual payments independently reviewed","detective","manual","weekly","Procure to Pay","RAHUL00","false"),
    ("P2P-031","Requisition","Non-approved categories blocked","preventive","automated","continuous","Procure to Pay","VIKRA04","false"),
    ("P2P-032","Requisition","Emergency purchases reviewed","detective","manual","weekly","Procure to Pay","VIKRA04","false"),
    ("P2P-033","Sourcing","Related-party suppliers identified","detective","automated","quarterly","Procure to Pay","VIKRA04","false"),
    ("P2P-034","Vendor","Vendor inactivity reviewed","detective","automated","quarterly","Procure to Pay","RAHUL00","false"),
    ("P2P-035","Vendor","Vendor master changes reviewed","detective","automated","daily","Procure to Pay","RAHUL00","false"),
    # ── EXPANDED: O2C additional (23 more → 35 total) ──
    ("O2C-013","Sales Order","Orders outside approved terms reviewed","detective","manual","weekly","Order to Cash","ANJAL05","false"),
    ("O2C-014","Delivery","Delivery quantity reconciled to order","detective","automated","continuous","Order to Cash","ANJAL05","false"),
    ("O2C-015","Delivery","Unauthorized delivery changes detected","detective","automated","continuous","Order to Cash","ANJAL05","false"),
    ("O2C-016","Delivery","Goods issue restricted to authorized users","preventive","automated","continuous","Order to Cash","ANJAL05","true"),
    ("O2C-017","Billing","Billing completeness monitored","detective","automated","daily","Order to Cash","ANJAL05","true"),
    ("O2C-018","Billing","Billing cut-off reviewed","detective","manual","monthly","Order to Cash","ANJAL05","false"),
    ("O2C-019","Billing","Invoice pricing validated","detective","automated","continuous","Order to Cash","ANJAL05","false"),
    ("O2C-020","Billing","Manual invoices reviewed","detective","manual","weekly","Order to Cash","ANJAL05","false"),
    ("O2C-021","AR","Overdue balances escalated","detective","automated","weekly","Order to Cash","RAHUL00","false"),
    ("O2C-022","AR","Bad-debt provisions reviewed","detective","manual","quarterly","Order to Cash","RAHUL00","false"),
    ("O2C-023","Cash","Customer receipts reconciled","detective","automated","daily","Order to Cash","RAHUL00","false"),
    ("O2C-024","Cash","Unapplied cash reviewed","detective","manual","weekly","Order to Cash","RAHUL00","false"),
    ("O2C-025","Returns","Returned quantities validated","detective","automated","continuous","Order to Cash","ANJAL05","false"),
    ("O2C-026","Pricing","Pricing-condition changes reviewed","detective","automated","daily","Order to Cash","ANJAL05","false"),
    ("O2C-027","Pricing","Unauthorized discounts detected","detective","automated","continuous","Order to Cash","ANJAL05","false"),
    ("O2C-028","Commission","Sales commissions validated","detective","manual","monthly","Order to Cash","ANJAL05","false"),
    ("O2C-029","Credit","Credit limit overrides reviewed","detective","automated","daily","Order to Cash","ANJAL05","false"),
    ("O2C-030","Credit","Blocked customers cannot create orders","preventive","automated","continuous","Order to Cash","ANJAL05","true"),
    ("O2C-031","Customer","Customer bank changes verified","preventive","manual","continuous","Order to Cash","ANJAL05","true"),
    ("O2C-032","Customer","Duplicate customers detected","detective","automated","continuous","Order to Cash","ANJAL05","true"),
    ("O2C-033","Sales Order","Manual price overrides reviewed","detective","automated","daily","Order to Cash","ANJAL05","false"),
    ("O2C-034","Sales Order","Excessive discounts detected","detective","automated","daily","Order to Cash","ANJAL05","false"),
    ("O2C-035","Sales Order","Orders exceeding credit blocked","preventive","automated","continuous","Order to Cash","ANJAL05","true"),
    # ── EXPANDED: H2R additional (15 more → 25 total) ──
    ("H2R-011","Hiring","Employee documentation validated","detective","manual","continuous","Hire to Retire","SNEHA03","false"),
    ("H2R-012","Compensation","Bonus changes require approval","preventive","manual","continuous","Hire to Retire","SNEHA03","true"),
    ("H2R-013","Payroll","Unusual payroll changes detected","detective","automated","continuous","Hire to Retire","SNEHA03","true"),
    ("H2R-014","Payroll","Duplicate payroll payments detected","detective","automated","continuous","Hire to Retire","SNEHA03","true"),
    ("H2R-015","Payroll","Payroll exceptions reviewed","detective","manual","monthly","Hire to Retire","SNEHA03","false"),
    ("H2R-016","Time","Overtime requires approval","preventive","manual","continuous","Hire to Retire","SNEHA03","false"),
    ("H2R-017","Time","Excessive overtime monitored","detective","automated","monthly","Hire to Retire","SNEHA03","false"),
    ("H2R-018","Benefits","Benefit changes require approval","preventive","manual","continuous","Hire to Retire","SNEHA03","false"),
    ("H2R-019","Termination","Final settlement reviewed","detective","manual","continuous","Hire to Retire","SNEHA03","false"),
    ("H2R-020","Payroll","Payroll master-data exceptions reviewed","detective","automated","monthly","Hire to Retire","SNEHA03","false"),
    ("H2R-021","Payroll","Payroll bank accounts monitored for duplicates","detective","automated","monthly","Hire to Retire","SNEHA03","false"),
    ("H2R-022","HR","Employee-to-cost-center assignments reviewed","detective","manual","quarterly","Hire to Retire","SNEHA03","false"),
    ("H2R-023","HR","Periodic employee master certification","detective","manual","annual","Hire to Retire","SNEHA03","true"),
    ("H2R-024","Master Data","Sensitive employee changes reviewed","detective","automated","daily","Hire to Retire","SNEHA03","true"),
    ("H2R-025","Master Data","Bank-account changes verified","preventive","manual","continuous","Hire to Retire","SNEHA03","true"),
    # ── EXPANDED: A2R additional (14 more → 20 total) ──
    ("A2R-007","Capitalization","Asset class reviewed","detective","manual","continuous","Acquire to Retire","RAHUL00","false"),
    ("A2R-008","Capitalization","Useful life reviewed","detective","manual","continuous","Acquire to Retire","RAHUL00","false"),
    ("A2R-009","Capitalization","Capitalized asset has supporting invoice","detective","automated","continuous","Acquire to Retire","RAHUL00","false"),
    ("A2R-010","Asset Master","Asset master changes reviewed","detective","automated","daily","Acquire to Retire","RAHUL00","false"),
    ("A2R-011","Depreciation","Depreciation exceptions investigated","detective","automated","monthly","Acquire to Retire","RAHUL00","false"),
    ("A2R-012","Physical","Missing assets investigated","detective","manual","annual","Acquire to Retire","RAHUL00","false"),
    ("A2R-013","Impairment","Impairment indicators reviewed","detective","manual","quarterly","Acquire to Retire","RAHUL00","false"),
    ("A2R-014","Impairment","Impairment calculation approved","detective","manual","quarterly","Acquire to Retire","RAHUL00","false"),
    ("A2R-015","Disposal","Disposal proceeds reconciled","detective","automated","continuous","Acquire to Retire","RAHUL00","false"),
    ("A2R-016","Disposal","Gain loss calculation reviewed","detective","manual","continuous","Acquire to Retire","RAHUL00","false"),
    ("A2R-017","Lease","Lease accounting data validated","detective","manual","quarterly","Acquire to Retire","RAHUL00","false"),
    ("A2R-018","Reconciliation","Fixed asset subledger reconciles GL","detective","automated","monthly","Acquire to Retire","RAHUL00","true"),
    ("A2R-019","Reporting","Asset register periodically certified","detective","manual","annual","Acquire to Retire","RAHUL00","true"),
    ("A2R-020","Acquisition","Asset purchase validated against budget","preventive","automated","continuous","Acquire to Retire","RAHUL00","true"),
    # ── EXPANDED: INV additional (20 more → 25 total) ──
    ("INV-006","Inventory","Cycle counts performed","detective","manual","monthly","Inventory Management","VIKRA04","true"),
    ("INV-007","Inventory","Inventory differences investigated","detective","automated","continuous","Inventory Management","VIKRA04","false"),
    ("INV-008","Inventory","Large adjustments escalated","detective","automated","continuous","Inventory Management","VIKRA04","false"),
    ("INV-009","Inventory","Obsolete inventory identified","detective","automated","quarterly","Inventory Management","VIKRA04","false"),
    ("INV-010","Inventory","Slow-moving inventory reviewed","detective","automated","quarterly","Inventory Management","VIKRA04","false"),
    ("INV-011","Inventory","Stock balances reconcile with GL","detective","automated","monthly","Inventory Management","VIKRA04","true"),
    ("INV-012","Goods Movement","Unusual goods movements detected","detective","automated","daily","Inventory Management","VIKRA04","false"),
    ("INV-013","Goods Movement","Backdated goods movements monitored","detective","automated","continuous","Inventory Management","VIKRA04","false"),
    ("INV-014","Transfer","Stock transfers require authorization","preventive","manual","continuous","Inventory Management","VIKRA04","false"),
    ("INV-015","Transfer","Transfer quantities reconciled","detective","automated","continuous","Inventory Management","VIKRA04","false"),
    ("INV-016","Warehouse","Picking requires authorized order","preventive","automated","continuous","Inventory Management","VIKRA04","true"),
    ("INV-017","Warehouse","Picking quantity validated","detective","automated","continuous","Inventory Management","VIKRA04","false"),
    ("INV-018","Warehouse","Packing reconciled with delivery","detective","automated","continuous","Inventory Management","VIKRA04","false"),
    ("INV-019","Warehouse","Shipping matched with approved delivery","preventive","automated","continuous","Inventory Management","VIKRA04","true"),
    ("INV-020","Warehouse","Warehouse adjustments reviewed","detective","manual","weekly","Inventory Management","VIKRA04","false"),
    ("INV-021","Scrap","Abnormal scrap investigated","detective","automated","monthly","Inventory Management","VIKRA04","false"),
    ("INV-022","Consignment","Consignment stock reconciled","detective","manual","monthly","Inventory Management","VIKRA04","false"),
    ("INV-023","Vendor Stock","Vendor-owned inventory reconciled","detective","manual","quarterly","Inventory Management","VIKRA04","false"),
    ("INV-024","Inventory","Inventory valuation exceptions investigated","detective","automated","monthly","Inventory Management","VIKRA04","false"),
    ("INV-025","Scrap","Scrap requires authorization","preventive","manual","continuous","Inventory Management","VIKRA04","false"),
    # ── EXPANDED: PP additional (19 more → 25 total) ──
    ("PP-007","Routing","Routing changes require approval","preventive","manual","continuous","Plan to Produce","VIKRA04","false"),
    ("PP-008","Production Order","High-value production orders require approval","preventive","manual","continuous","Plan to Produce","VIKRA04","true"),
    ("PP-009","Production","Excess consumption investigated","detective","automated","daily","Plan to Produce","VIKRA04","false"),
    ("PP-010","Production","Production confirmations reviewed","detective","automated","daily","Plan to Produce","VIKRA04","false"),
    ("PP-011","Production","Backdated confirmations monitored","detective","automated","continuous","Plan to Produce","VIKRA04","false"),
    ("PP-012","Production","Abnormal production variance investigated","detective","automated","monthly","Plan to Produce","VIKRA04","false"),
    ("PP-013","WIP","WIP aging reviewed","detective","manual","monthly","Plan to Produce","VIKRA04","false"),
    ("PP-014","Costing","Product costing reviewed","detective","manual","quarterly","Plan to Produce","VIKRA04","false"),
    ("PP-015","Variance","Production variance analyzed","detective","automated","monthly","Plan to Produce","VIKRA04","false"),
    ("PP-016","Variance","Material price variance investigated","detective","automated","monthly","Plan to Produce","VIKRA04","false"),
    ("PP-017","Variance","Labor variance investigated","detective","automated","monthly","Plan to Produce","VIKRA04","false"),
    ("PP-018","Variance","Overhead variance reviewed","detective","automated","monthly","Plan to Produce","VIKRA04","false"),
    ("PP-019","Settlement","Production-order settlement reviewed","detective","manual","monthly","Plan to Produce","VIKRA04","false"),
    ("PP-020","Production","Closed production orders reviewed","detective","manual","quarterly","Plan to Produce","VIKRA04","false"),
    ("PP-021","Planning","MRP exceptions reviewed","detective","automated","daily","Plan to Produce","VIKRA04","false"),
    ("PP-022","Planning","Material availability validated","detective","automated","continuous","Plan to Produce","VIKRA04","false"),
    ("PP-023","Planning","Capacity exceptions reviewed","detective","automated","daily","Plan to Produce","VIKRA04","false"),
    ("PP-024","BOM","BOM changes reviewed","detective","automated","daily","Plan to Produce","VIKRA04","false"),
    ("PP-025","Production","Scrap quantities monitored","detective","automated","daily","Plan to Produce","VIKRA04","false"),
    # ── EXPANDED: TR additional (14 more → 20 total) ──
    ("TR-007","Bank","Unreconciled bank items reviewed","detective","manual","monthly","Treasury and Cash","RAHUL00","false"),
    ("TR-008","Cash","Daily cash position reviewed","detective","manual","daily","Treasury and Cash","RAHUL00","false"),
    ("TR-009","Cash","Cash forecast reviewed","detective","manual","weekly","Treasury and Cash","RAHUL00","false"),
    ("TR-010","Payment","Manual payments reviewed","detective","manual","weekly","Treasury and Cash","RAHUL00","false"),
    ("TR-011","Payment","Payments to blocked accounts prevented","preventive","automated","continuous","Treasury and Cash","RAHUL00","true"),
    ("TR-012","Payment","Payment beneficiary changes reviewed","detective","automated","daily","Treasury and Cash","RAHUL00","false"),
    ("TR-013","FX","FX transactions authorized","preventive","manual","continuous","Treasury and Cash","RAHUL00","false"),
    ("TR-014","FX","FX valuation reviewed","detective","manual","monthly","Treasury and Cash","RAHUL00","false"),
    ("TR-015","Investment","Investment transactions require approval","preventive","manual","continuous","Treasury and Cash","RAHUL00","true"),
    ("TR-016","Debt","Debt transactions approved","preventive","manual","continuous","Treasury and Cash","RAHUL00","true"),
    ("TR-017","Debt","Debt balances reconciled","detective","manual","monthly","Treasury and Cash","RAHUL00","false"),
    ("TR-018","Treasury","Treasury confirmations independently verified","detective","manual","continuous","Treasury and Cash","RAHUL00","false"),
    ("TR-019","Treasury","Bank fees reviewed","detective","automated","monthly","Treasury and Cash","RAHUL00","false"),
    ("TR-020","Treasury","Treasury positions reconciled to GL","detective","automated","monthly","Treasury and Cash","RAHUL00","true"),
    # ── EXPANDED: TAX additional (16 more → 20 total) ──
    ("TAX-005","Tax","Tax postings reconcile to GL","detective","automated","monthly","Tax Management","RAHUL00","true"),
    ("TAX-006","GST VAT","Tax-credit exceptions reviewed","detective","automated","monthly","Tax Management","RAHUL00","false"),
    ("TAX-007","GST VAT","Invalid tax registrations detected","detective","automated","quarterly","Tax Management","RAHUL00","false"),
    ("TAX-008","Withholding","Withholding-tax configuration reviewed","detective","manual","quarterly","Tax Management","RAHUL00","false"),
    ("TAX-009","Withholding","Withholding tax reconciled","detective","automated","monthly","Tax Management","RAHUL00","false"),
    ("TAX-010","Income Tax","Tax provision reviewed","detective","manual","quarterly","Tax Management","RAHUL00","false"),
    ("TAX-011","Income Tax","Tax liability reconciles with GL","detective","automated","monthly","Tax Management","RAHUL00","false"),
    ("TAX-012","Tax","Late tax liabilities identified","detective","automated","monthly","Tax Management","RAHUL00","false"),
    ("TAX-013","Tax","Tax exemptions require approval","preventive","manual","continuous","Tax Management","RAHUL00","false"),
    ("TAX-014","Tax","Related-party tax transactions reviewed","detective","manual","quarterly","Tax Management","RAHUL00","false"),
    ("TAX-015","Transfer Pricing","Transfer-pricing calculations reviewed","detective","manual","quarterly","Tax Management","RAHUL00","false"),
    ("TAX-016","Tax","Tax reconciliation differences investigated","detective","automated","monthly","Tax Management","RAHUL00","false"),
    ("TAX-017","Tax","Regulatory tax reports management sign-off","detective","manual","monthly","Tax Management","RAHUL00","true"),
    ("TAX-018","Tax Master","Tax-code changes reviewed","detective","automated","daily","Tax Management","RAHUL00","false"),
    ("TAX-019","Tax","Output tax validated","detective","automated","continuous","Tax Management","RAHUL00","true"),
    ("TAX-020","Tax Payment","Tax payment requires approval","preventive","manual","continuous","Tax Management","RAHUL00","true"),
    # ── EXPANDED: MD additional (19 more → 25 total) ──
    ("MD-007","Customer","Customer credit data reviewed","detective","manual","quarterly","Master Data","ANJAL05","false"),
    ("MD-008","Customer","Customer bank changes verified","preventive","manual","continuous","Master Data","ANJAL05","true"),
    ("MD-009","Customer","Inactive customers reviewed","detective","automated","quarterly","Master Data","ANJAL05","false"),
    ("MD-010","Material","Material changes reviewed","detective","automated","daily","Master Data","VIKRA04","false"),
    ("MD-011","Material","Duplicate materials detected","detective","automated","continuous","Master Data","VIKRA04","true"),
    ("MD-012","Material","Material classification validated","detective","manual","quarterly","Master Data","VIKRA04","false"),
    ("MD-013","Material","Obsolete materials reviewed","detective","automated","quarterly","Master Data","VIKRA04","false"),
    ("MD-014","GL","GL account changes reviewed","detective","automated","daily","Master Data","RAHUL00","false"),
    ("MD-015","Cost Center","Cost-center creation requires approval","preventive","manual","continuous","Master Data","RAHUL00","true"),
    ("MD-016","Cost Center","Cost-center changes reviewed","detective","automated","daily","Master Data","RAHUL00","false"),
    ("MD-017","Profit Center","Profit-center creation requires approval","preventive","manual","continuous","Master Data","RAHUL00","true"),
    ("MD-018","Profit Center","Profit-center changes reviewed","detective","automated","daily","Master Data","RAHUL00","false"),
    ("MD-019","Bank","Bank master changes require approval","preventive","manual","continuous","Master Data","RAHUL00","true"),
    ("MD-020","HR","Employee master changes reviewed","detective","automated","daily","Master Data","SNEHA03","false"),
    ("MD-021","Master Data","Sensitive-field changes monitored","detective","automated","continuous","Master Data","AMIT002","true"),
    ("MD-022","Master Data","Periodic master-data certification","detective","manual","annual","Master Data","RAHUL00","true"),
    ("MD-023","Vendor","Vendor tax information validated","detective","automated","continuous","Master Data","RAHUL00","false"),
    ("MD-024","Vendor","Inactive vendors reviewed","detective","automated","quarterly","Master Data","RAHUL00","false"),
    ("MD-025","Customer","Duplicate customers detected","detective","automated","continuous","Master Data","ANJAL05","true"),
    # ── EXPANDED: PS additional (12 more → 15 total) ──
    ("PS-004","Cost Monitoring","Actual costs compared with budget","detective","automated","monthly","Project Management","RAHUL00","true"),
    ("PS-005","Cost Monitoring","Cost overruns escalated","detective","automated","monthly","Project Management","RAHUL00","false"),
    ("PS-006","Project","Project commitments reviewed","detective","automated","monthly","Project Management","RAHUL00","false"),
    ("PS-007","Project","Purchase commitments reconciled","detective","automated","monthly","Project Management","RAHUL00","false"),
    ("PS-008","Project","WBS changes reviewed","detective","automated","daily","Project Management","RAHUL00","false"),
    ("PS-009","Project","Project master changes monitored","detective","automated","continuous","Project Management","RAHUL00","false"),
    ("PS-010","Project","Timesheet charges validated","detective","automated","weekly","Project Management","RAHUL00","false"),
    ("PS-011","Project","Project revenue reconciled","detective","automated","monthly","Project Management","RAHUL00","false"),
    ("PS-012","Project","Project billing reviewed","detective","manual","monthly","Project Management","RAHUL00","false"),
    ("PS-013","Settlement","Project settlement approved","preventive","manual","continuous","Project Management","RAHUL00","true"),
    ("PS-014","Project","Capital projects reviewed for capitalization","detective","manual","quarterly","Project Management","RAHUL00","false"),
    ("PS-015","Project","Project closure independently reviewed","detective","manual","continuous","Project Management","RAHUL00","false"),
    # ── EXPANDED: QM additional (7 more → 10 total) ──
    ("QM-004","Quality","Quality deviations require investigation","detective","manual","continuous","Quality Management","VIKRA04","false"),
    ("QM-005","Quality","Quality notifications reviewed","detective","manual","weekly","Quality Management","VIKRA04","false"),
    ("QM-006","Vendor Quality","Supplier quality issues monitored","detective","automated","continuous","Quality Management","VIKRA04","false"),
    ("QM-007","Customer Quality","Customer complaints tracked","detective","manual","continuous","Quality Management","VIKRA04","false"),
    ("QM-008","Quality","Quality certificates validated","detective","manual","continuous","Quality Management","VIKRA04","false"),
    ("QM-009","Quality","Quality metrics reviewed by management","detective","manual","monthly","Quality Management","VIKRA04","false"),
    ("QM-010","Inspection","Inspection results require authorized entry","preventive","automated","continuous","Quality Management","VIKRA04","true"),
    # ── EXPANDED: PM additional (8 more → 10 total) ──
    ("PM-003","Maintenance","Overdue preventive maintenance escalated","detective","automated","weekly","Plant Maintenance","AMIT002","false"),
    ("PM-004","Maintenance","Emergency maintenance reviewed","detective","manual","weekly","Plant Maintenance","AMIT002","false"),
    ("PM-005","Costs","Maintenance costs monitored","detective","automated","monthly","Plant Maintenance","AMIT002","false"),
    ("PM-006","Spare Parts","Spare-parts consumption reconciled","detective","automated","monthly","Plant Maintenance","AMIT002","false"),
    ("PM-007","Maintenance","External service invoices matched to orders","detective","automated","continuous","Plant Maintenance","AMIT002","false"),
    ("PM-008","Maintenance","Asset maintenance history reviewed","detective","manual","quarterly","Plant Maintenance","AMIT002","false"),
    ("PM-009","Maintenance","Maintenance-order settlement reviewed","detective","manual","monthly","Plant Maintenance","AMIT002","false"),
    ("PM-010","Maintenance","Maintenance notification requires authorization","preventive","manual","continuous","Plant Maintenance","AMIT002","true"),
    # ── EXPANDED: IC additional (12 more → 15 total) ──
    ("IC-004","Intercompany","Unmatched balances investigated","detective","manual","monthly","Intercompany","RAHUL00","false"),
    ("IC-005","Intercompany","Intercompany pricing reviewed","detective","manual","quarterly","Intercompany","RAHUL00","false"),
    ("IC-006","Intercompany","Intercompany invoices validated","detective","automated","monthly","Intercompany","RAHUL00","false"),
    ("IC-007","Intercompany","Related-party transactions reviewed","detective","manual","quarterly","Intercompany","RAHUL00","true"),
    ("IC-008","Elimination","Elimination differences investigated","detective","automated","quarterly","Intercompany","RAHUL00","false"),
    ("IC-009","Consolidation","Consolidation journals require approval","preventive","manual","quarterly","Intercompany","RAHUL00","true"),
    ("IC-010","Consolidation","Consolidation data reconciled","detective","automated","quarterly","Intercompany","RAHUL00","true"),
    ("IC-011","Consolidation","Subsidiary reporting packages reviewed","detective","manual","quarterly","Intercompany","RAHUL00","false"),
    ("IC-012","Consolidation","Currency translation reviewed","detective","manual","quarterly","Intercompany","RAHUL00","false"),
    ("IC-013","Consolidation","Consolidated financial statements reviewed","detective","manual","quarterly","Intercompany","RAHUL00","true"),
    ("IC-014","Consolidation","IC profit elimination validated","detective","automated","quarterly","Intercompany","RAHUL00","false"),
    ("IC-015","Consolidation","Consolidation exceptions resolved before reporting","detective","manual","quarterly","Intercompany","RAHUL00","false"),
    # ── EXPANDED: ITGC additional (8 more → 25 total) ──
    ("ITGC-018","Access","Generic shared accounts monitored","detective","automated","monthly","IT General Controls","AMIT002","false"),
    ("ITGC-019","Change","Transport approvals documented","detective","manual","continuous","IT General Controls","AMIT002","false"),
    ("ITGC-020","Change","Unauthorized production changes detected","detective","automated","continuous","IT General Controls","AMIT002","true"),
    ("ITGC-021","Configuration","Critical security parameters reviewed","detective","manual","quarterly","IT General Controls","DEEPA09","false"),
    ("ITGC-022","Operations","Critical jobs monitored","detective","automated","continuous","IT General Controls","AMIT002","false"),
    ("ITGC-023","Operations","Failed background jobs reviewed","detective","automated","daily","IT General Controls","AMIT002","false"),
    ("ITGC-024","Operations","Interface failures monitored","detective","automated","continuous","IT General Controls","AMIT002","true"),
    ("ITGC-025","Access","Periodic privileged-user certification","detective","manual","quarterly","IT General Controls","AMIT002","true"),
    # ── EXPANDED: INT additional (11 more → 15 total) ──
    ("INT-005","Interface","Failed transactions investigated","detective","manual","daily","Interfaces and Data","AMIT002","false"),
    ("INT-006","Interface","Duplicate interface transactions detected","detective","automated","continuous","Interfaces and Data","AMIT002","false"),
    ("INT-007","Interface","Interface processing dates monitored","detective","automated","daily","Interfaces and Data","AMIT002","false"),
    ("INT-008","Interface","Unauthorized interfaces detected","detective","automated","monthly","Interfaces and Data","AMIT002","false"),
    ("INT-009","Data","Source-to-system data reconciliation","detective","automated","daily","Interfaces and Data","AMIT002","true"),
    ("INT-010","Data","Critical master-data interfaces monitored","detective","automated","continuous","Interfaces and Data","AMIT002","false"),
    ("INT-011","Data","Data transformation rules reviewed","detective","manual","quarterly","Interfaces and Data","AMIT002","false"),
    ("INT-012","Data","Data migration reconciliation","detective","automated","continuous","Interfaces and Data","AMIT002","false"),
    ("INT-013","Data","Migration exceptions reviewed","detective","manual","continuous","Interfaces and Data","AMIT002","false"),
    ("INT-014","Data","Interface record counts reconciled","detective","automated","daily","Interfaces and Data","AMIT002","true"),
    ("INT-015","Data","Interface controls periodically certified","detective","manual","annual","Interfaces and Data","AMIT002","true"),
    # ── EXPANDED: COMP additional (9 more → 15 total) ──
    ("COMP-007","SOX","Remediation actions tracked","detective","manual","continuous","Compliance","SURES08","true"),
    ("COMP-008","Compliance","Regulatory changes assessed","detective","manual","continuous","Compliance","SURES08","false"),
    ("COMP-009","Compliance","Compliance obligations mapped to controls","preventive","manual","annual","Compliance","SURES08","true"),
    ("COMP-010","Compliance","Compliance exceptions escalated","detective","manual","continuous","Compliance","SURES08","false"),
    ("COMP-011","Anti-Bribery","High-risk transactions reviewed","detective","manual","quarterly","Compliance","SURES08","false"),
    ("COMP-012","Related Party","Related-party transactions require review","detective","manual","quarterly","Compliance","SURES08","true"),
    ("COMP-013","Retention","Required records retained","preventive","automated","continuous","Compliance","AMIT002","true"),
    ("COMP-014","Compliance","Regulatory reports reviewed","detective","manual","monthly","Compliance","SURES08","false"),
    ("COMP-015","SOX","Control deficiencies documented","detective","manual","continuous","Compliance","SURES08","true"),
]

for c in controls:
    cid, sub, name, ct, nat, freq, proc, own, key = c
    lines.append(f"INSERT INTO process_controls (tenant_id,control_id,name,objective,control_type,control_nature,frequency,process_name,subprocess_name,owner_id,key_control,status,version,is_active,created_at,updated_at) VALUES ('{T}','{cid}','{name}','Ensure {name.lower()}','{ct}','{nat}','{freq}','{proc}','{sub}','{own}',{key},'active',1,true,NOW(),NOW());")

lines.append(f"SELECT 'subprocesses' as item, count(*) as cnt FROM subprocesses WHERE tenant_id='{T}' UNION ALL SELECT 'objectives', count(*) FROM control_objectives WHERE tenant_id='{T}' UNION ALL SELECT 'controls', count(*) FROM process_controls WHERE tenant_id='{T}' UNION ALL SELECT 'key_controls', count(*) FROM process_controls WHERE tenant_id='{T}' AND key_control=true ORDER BY item;")

sql = "\n".join(lines)

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect("212.47.75.51", username="root", password="l4yiVUCmI51v3aJ4g0wZvg", timeout=10)
sftp = ssh.open_sftp()
with sftp.open("/tmp/seed_ctrls.sql", "w") as f:
    f.write(sql)
sftp.close()

stdin, stdout, stderr = ssh.exec_command("sudo -u postgres psql -d governexplus -f /tmp/seed_ctrls.sql 2>&1 | tail -15", timeout=30)
print(stdout.read().decode("utf-8", errors="replace"))
print(f"\nTotal controls defined: {len(controls)}")
ssh.close()
