"""
API Schemas Package
Pydantic models for request/response validation
"""

from .user import (
    UserStatus,
    UserType,
    RiskLevel,
    UserCreate,
    UserUpdate,
    UserFilters,
    RoleAssignment,
    UserSummary,
    UserDetailResponse,
    UserResponse,
    PaginatedUsersResponse,
    UserStatsResponse,
    RoleInfo,
    ViolationInfo,
    EntitlementInfo,
    BulkOperationResult,
)

from .role import (
    RoleType,
    RoleStatus,
    RoleCreate,
    RoleUpdate,
    RoleFilters,
    RoleSummary,
    RoleDetailResponse,
    RoleResponse,
    PaginatedRolesResponse,
    RoleStatsResponse,
    PermissionCreate,
    PermissionInfo,
    CompositeRoleCreate,
    DerivedRoleCreate,
    BusinessRoleCreate,
    BusinessRoleSummary,
    RoleCatalogEntry,
)

from .risk import (
    ViolationStatus,
    ViolationSeverity,
    ViolationType,
    ViolationCreate,
    ViolationUpdate,
    ViolationFilters,
    ViolationSummary,
    ViolationDetailResponse,
    ViolationResponse,
    PaginatedViolationsResponse,
    ViolationStatsResponse,
    SodRuleCreate,
    SodRuleUpdate,
    SodRuleSummary,
    SodRuleDetailResponse,
    PaginatedSodRulesResponse,
    RiskAnalysisResult,
    RoleSimulationResult,
)

from .auth import (
    LoginRequest,
    RefreshTokenRequest,
    ChangePasswordRequest,
    TokenResponse,
    UserInfoResponse,
    ProfileResponse,
)

__all__ = [
    # User schemas
    "UserStatus",
    "UserType",
    "RiskLevel",
    "UserCreate",
    "UserUpdate",
    "UserFilters",
    "RoleAssignment",
    "UserSummary",
    "UserDetailResponse",
    "UserResponse",
    "PaginatedUsersResponse",
    "UserStatsResponse",
    "RoleInfo",
    "ViolationInfo",
    "EntitlementInfo",
    "BulkOperationResult",
    # Role schemas
    "RoleType",
    "RoleStatus",
    "RoleCreate",
    "RoleUpdate",
    "RoleFilters",
    "RoleSummary",
    "RoleDetailResponse",
    "RoleResponse",
    "PaginatedRolesResponse",
    "RoleStatsResponse",
    "PermissionCreate",
    "PermissionInfo",
    "CompositeRoleCreate",
    "DerivedRoleCreate",
    "BusinessRoleCreate",
    "BusinessRoleSummary",
    "RoleCatalogEntry",
    # Risk schemas
    "ViolationStatus",
    "ViolationSeverity",
    "ViolationType",
    "ViolationCreate",
    "ViolationUpdate",
    "ViolationFilters",
    "ViolationSummary",
    "ViolationDetailResponse",
    "ViolationResponse",
    "PaginatedViolationsResponse",
    "ViolationStatsResponse",
    "SodRuleCreate",
    "SodRuleUpdate",
    "SodRuleSummary",
    "SodRuleDetailResponse",
    "PaginatedSodRulesResponse",
    "RiskAnalysisResult",
    "RoleSimulationResult",
    # Auth schemas
    "LoginRequest",
    "RefreshTokenRequest",
    "ChangePasswordRequest",
    "TokenResponse",
    "UserInfoResponse",
    "ProfileResponse",
]
